# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-04-27T08:28:54+00:00

from __future__ import annotations

from datetime import date as date_aliased
from datetime import timedelta
from enum import Enum
from typing import Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    NaiveDatetime,
    EmailStr,
    Field,
    RootModel,
    SecretStr,
    confloat,
    conint,
    constr,
)


class Activity(BaseModel):
    id: str = Field(..., title='Id')
    start_date_local: NaiveDatetime | None = Field(None, title='Start Date Local')


class ActivityUpdate(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')


class AltitudeSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    gain: int | float | None = Field(None, title='Gain')
    loss: int | float | None = Field(None, title='Loss')
    min: int | float | None = Field(None, title='Min')
    max: int | float | None = Field(None, title='Max')


class ApplicationCreate(BaseModel):
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    description: constr(max_length=500) | None = Field(None, title='Description')
    redirect_uris: list[AnyUrl] | None = Field(None, title='Redirect Uris')
    page: str | None = Field(None, title='Page')
    generate_secret: bool | None = Field(False, title='Generate Secret')


class ApplicationCreateOrUpdate(BaseModel):
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    url: AnyUrl | None = Field(None, title='Url')
    image: AnyUrl | None = Field(None, title='Image')
    redirect_uris: list[AnyUrl] | None = Field(None, title='Redirect Uris')
    privacy_statement: AnyUrl | None = Field(None, title='Privacy Statement')
    published: bool | None = Field(False, title='Published')
    webhook_endpoints: list[AnyUrl] | None = Field(None, title='Webhook Endpoints')
    webhook_secret: SecretStr | None = Field(None, title='Webhook Secret')


class ApplicationListItem(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    page_slug: str | None = Field(None, title='Page Slug')


class ApplicationMemberRole(Enum):
    owner = 'owner'
    member = 'member'


class Prompt(Enum):
    none = 'none'
    login = 'login'
    consent = 'consent'
    select_account = 'select_account'


class BackfillError(BaseModel):
    error: str = Field(..., title='Error')


class BackfillStatus(BaseModel):
    backfill_loaded_until: AwareDatetime | None = Field(
        ..., title='Backfill Loaded Until'
    )


class BodyAddEmailPartialsAddEmailPost(BaseModel):
    email: EmailStr = Field(..., title='Email')


class BodyCreateApplicationSecretApplicationsApplicationIdSecretsPost(BaseModel):
    label: str = Field(..., title='Label')


class BodyCreatePageApiV1PagesPost(BaseModel):
    application_id: str = Field(..., title='Application Id')
    slug: str = Field(..., title='Slug')


class BodyCreatePageApplicationsApplicationIdPagePost(BaseModel):
    slug: str = Field(..., title='Slug')


class BodyCreateTagTagsPost(BaseModel):
    tag: str = Field(..., title='Tag')


class BodyDeployPageApiV1PagesSlugDeployPut(BaseModel):
    files: list[bytes] = Field(..., title='Files')


class BodyDeployPageApplicationsApplicationIdPageDeployPost(BaseModel):
    files: list[bytes] = Field(..., title='Files')


class Tz(Enum):
    Africa_Abidjan = 'Africa/Abidjan'
    Africa_Accra = 'Africa/Accra'
    Africa_Addis_Ababa = 'Africa/Addis_Ababa'
    Africa_Algiers = 'Africa/Algiers'
    Africa_Asmara = 'Africa/Asmara'
    Africa_Asmera = 'Africa/Asmera'
    Africa_Bamako = 'Africa/Bamako'
    Africa_Bangui = 'Africa/Bangui'
    Africa_Banjul = 'Africa/Banjul'
    Africa_Bissau = 'Africa/Bissau'
    Africa_Blantyre = 'Africa/Blantyre'
    Africa_Brazzaville = 'Africa/Brazzaville'
    Africa_Bujumbura = 'Africa/Bujumbura'
    Africa_Cairo = 'Africa/Cairo'
    Africa_Casablanca = 'Africa/Casablanca'
    Africa_Ceuta = 'Africa/Ceuta'
    Africa_Conakry = 'Africa/Conakry'
    Africa_Dakar = 'Africa/Dakar'
    Africa_Dar_es_Salaam = 'Africa/Dar_es_Salaam'
    Africa_Djibouti = 'Africa/Djibouti'
    Africa_Douala = 'Africa/Douala'
    Africa_El_Aaiun = 'Africa/El_Aaiun'
    Africa_Freetown = 'Africa/Freetown'
    Africa_Gaborone = 'Africa/Gaborone'
    Africa_Harare = 'Africa/Harare'
    Africa_Johannesburg = 'Africa/Johannesburg'
    Africa_Juba = 'Africa/Juba'
    Africa_Kampala = 'Africa/Kampala'
    Africa_Khartoum = 'Africa/Khartoum'
    Africa_Kigali = 'Africa/Kigali'
    Africa_Kinshasa = 'Africa/Kinshasa'
    Africa_Lagos = 'Africa/Lagos'
    Africa_Libreville = 'Africa/Libreville'
    Africa_Lome = 'Africa/Lome'
    Africa_Luanda = 'Africa/Luanda'
    Africa_Lubumbashi = 'Africa/Lubumbashi'
    Africa_Lusaka = 'Africa/Lusaka'
    Africa_Malabo = 'Africa/Malabo'
    Africa_Maputo = 'Africa/Maputo'
    Africa_Maseru = 'Africa/Maseru'
    Africa_Mbabane = 'Africa/Mbabane'
    Africa_Mogadishu = 'Africa/Mogadishu'
    Africa_Monrovia = 'Africa/Monrovia'
    Africa_Nairobi = 'Africa/Nairobi'
    Africa_Ndjamena = 'Africa/Ndjamena'
    Africa_Niamey = 'Africa/Niamey'
    Africa_Nouakchott = 'Africa/Nouakchott'
    Africa_Ouagadougou = 'Africa/Ouagadougou'
    Africa_Porto_Novo = 'Africa/Porto-Novo'
    Africa_Sao_Tome = 'Africa/Sao_Tome'
    Africa_Timbuktu = 'Africa/Timbuktu'
    Africa_Tripoli = 'Africa/Tripoli'
    Africa_Tunis = 'Africa/Tunis'
    Africa_Windhoek = 'Africa/Windhoek'
    America_Adak = 'America/Adak'
    America_Anchorage = 'America/Anchorage'
    America_Anguilla = 'America/Anguilla'
    America_Antigua = 'America/Antigua'
    America_Araguaina = 'America/Araguaina'
    America_Argentina_Buenos_Aires = 'America/Argentina/Buenos_Aires'
    America_Argentina_Catamarca = 'America/Argentina/Catamarca'
    America_Argentina_ComodRivadavia = 'America/Argentina/ComodRivadavia'
    America_Argentina_Cordoba = 'America/Argentina/Cordoba'
    America_Argentina_Jujuy = 'America/Argentina/Jujuy'
    America_Argentina_La_Rioja = 'America/Argentina/La_Rioja'
    America_Argentina_Mendoza = 'America/Argentina/Mendoza'
    America_Argentina_Rio_Gallegos = 'America/Argentina/Rio_Gallegos'
    America_Argentina_Salta = 'America/Argentina/Salta'
    America_Argentina_San_Juan = 'America/Argentina/San_Juan'
    America_Argentina_San_Luis = 'America/Argentina/San_Luis'
    America_Argentina_Tucuman = 'America/Argentina/Tucuman'
    America_Argentina_Ushuaia = 'America/Argentina/Ushuaia'
    America_Aruba = 'America/Aruba'
    America_Asuncion = 'America/Asuncion'
    America_Atikokan = 'America/Atikokan'
    America_Atka = 'America/Atka'
    America_Bahia = 'America/Bahia'
    America_Bahia_Banderas = 'America/Bahia_Banderas'
    America_Barbados = 'America/Barbados'
    America_Belem = 'America/Belem'
    America_Belize = 'America/Belize'
    America_Blanc_Sablon = 'America/Blanc-Sablon'
    America_Boa_Vista = 'America/Boa_Vista'
    America_Bogota = 'America/Bogota'
    America_Boise = 'America/Boise'
    America_Buenos_Aires = 'America/Buenos_Aires'
    America_Cambridge_Bay = 'America/Cambridge_Bay'
    America_Campo_Grande = 'America/Campo_Grande'
    America_Cancun = 'America/Cancun'
    America_Caracas = 'America/Caracas'
    America_Catamarca = 'America/Catamarca'
    America_Cayenne = 'America/Cayenne'
    America_Cayman = 'America/Cayman'
    America_Chicago = 'America/Chicago'
    America_Chihuahua = 'America/Chihuahua'
    America_Ciudad_Juarez = 'America/Ciudad_Juarez'
    America_Coral_Harbour = 'America/Coral_Harbour'
    America_Cordoba = 'America/Cordoba'
    America_Costa_Rica = 'America/Costa_Rica'
    America_Coyhaique = 'America/Coyhaique'
    America_Creston = 'America/Creston'
    America_Cuiaba = 'America/Cuiaba'
    America_Curacao = 'America/Curacao'
    America_Danmarkshavn = 'America/Danmarkshavn'
    America_Dawson = 'America/Dawson'
    America_Dawson_Creek = 'America/Dawson_Creek'
    America_Denver = 'America/Denver'
    America_Detroit = 'America/Detroit'
    America_Dominica = 'America/Dominica'
    America_Edmonton = 'America/Edmonton'
    America_Eirunepe = 'America/Eirunepe'
    America_El_Salvador = 'America/El_Salvador'
    America_Ensenada = 'America/Ensenada'
    America_Fort_Nelson = 'America/Fort_Nelson'
    America_Fort_Wayne = 'America/Fort_Wayne'
    America_Fortaleza = 'America/Fortaleza'
    America_Glace_Bay = 'America/Glace_Bay'
    America_Godthab = 'America/Godthab'
    America_Goose_Bay = 'America/Goose_Bay'
    America_Grand_Turk = 'America/Grand_Turk'
    America_Grenada = 'America/Grenada'
    America_Guadeloupe = 'America/Guadeloupe'
    America_Guatemala = 'America/Guatemala'
    America_Guayaquil = 'America/Guayaquil'
    America_Guyana = 'America/Guyana'
    America_Halifax = 'America/Halifax'
    America_Havana = 'America/Havana'
    America_Hermosillo = 'America/Hermosillo'
    America_Indiana_Indianapolis = 'America/Indiana/Indianapolis'
    America_Indiana_Knox = 'America/Indiana/Knox'
    America_Indiana_Marengo = 'America/Indiana/Marengo'
    America_Indiana_Petersburg = 'America/Indiana/Petersburg'
    America_Indiana_Tell_City = 'America/Indiana/Tell_City'
    America_Indiana_Vevay = 'America/Indiana/Vevay'
    America_Indiana_Vincennes = 'America/Indiana/Vincennes'
    America_Indiana_Winamac = 'America/Indiana/Winamac'
    America_Indianapolis = 'America/Indianapolis'
    America_Inuvik = 'America/Inuvik'
    America_Iqaluit = 'America/Iqaluit'
    America_Jamaica = 'America/Jamaica'
    America_Jujuy = 'America/Jujuy'
    America_Juneau = 'America/Juneau'
    America_Kentucky_Louisville = 'America/Kentucky/Louisville'
    America_Kentucky_Monticello = 'America/Kentucky/Monticello'
    America_Knox_IN = 'America/Knox_IN'
    America_Kralendijk = 'America/Kralendijk'
    America_La_Paz = 'America/La_Paz'
    America_Lima = 'America/Lima'
    America_Los_Angeles = 'America/Los_Angeles'
    America_Louisville = 'America/Louisville'
    America_Lower_Princes = 'America/Lower_Princes'
    America_Maceio = 'America/Maceio'
    America_Managua = 'America/Managua'
    America_Manaus = 'America/Manaus'
    America_Marigot = 'America/Marigot'
    America_Martinique = 'America/Martinique'
    America_Matamoros = 'America/Matamoros'
    America_Mazatlan = 'America/Mazatlan'
    America_Mendoza = 'America/Mendoza'
    America_Menominee = 'America/Menominee'
    America_Merida = 'America/Merida'
    America_Metlakatla = 'America/Metlakatla'
    America_Mexico_City = 'America/Mexico_City'
    America_Miquelon = 'America/Miquelon'
    America_Moncton = 'America/Moncton'
    America_Monterrey = 'America/Monterrey'
    America_Montevideo = 'America/Montevideo'
    America_Montreal = 'America/Montreal'
    America_Montserrat = 'America/Montserrat'
    America_Nassau = 'America/Nassau'
    America_New_York = 'America/New_York'
    America_Nipigon = 'America/Nipigon'
    America_Nome = 'America/Nome'
    America_Noronha = 'America/Noronha'
    America_North_Dakota_Beulah = 'America/North_Dakota/Beulah'
    America_North_Dakota_Center = 'America/North_Dakota/Center'
    America_North_Dakota_New_Salem = 'America/North_Dakota/New_Salem'
    America_Nuuk = 'America/Nuuk'
    America_Ojinaga = 'America/Ojinaga'
    America_Panama = 'America/Panama'
    America_Pangnirtung = 'America/Pangnirtung'
    America_Paramaribo = 'America/Paramaribo'
    America_Phoenix = 'America/Phoenix'
    America_Port_au_Prince = 'America/Port-au-Prince'
    America_Port_of_Spain = 'America/Port_of_Spain'
    America_Porto_Acre = 'America/Porto_Acre'
    America_Porto_Velho = 'America/Porto_Velho'
    America_Puerto_Rico = 'America/Puerto_Rico'
    America_Punta_Arenas = 'America/Punta_Arenas'
    America_Rainy_River = 'America/Rainy_River'
    America_Rankin_Inlet = 'America/Rankin_Inlet'
    America_Recife = 'America/Recife'
    America_Regina = 'America/Regina'
    America_Resolute = 'America/Resolute'
    America_Rio_Branco = 'America/Rio_Branco'
    America_Rosario = 'America/Rosario'
    America_Santa_Isabel = 'America/Santa_Isabel'
    America_Santarem = 'America/Santarem'
    America_Santiago = 'America/Santiago'
    America_Santo_Domingo = 'America/Santo_Domingo'
    America_Sao_Paulo = 'America/Sao_Paulo'
    America_Scoresbysund = 'America/Scoresbysund'
    America_Shiprock = 'America/Shiprock'
    America_Sitka = 'America/Sitka'
    America_St_Barthelemy = 'America/St_Barthelemy'
    America_St_Johns = 'America/St_Johns'
    America_St_Kitts = 'America/St_Kitts'
    America_St_Lucia = 'America/St_Lucia'
    America_St_Thomas = 'America/St_Thomas'
    America_St_Vincent = 'America/St_Vincent'
    America_Swift_Current = 'America/Swift_Current'
    America_Tegucigalpa = 'America/Tegucigalpa'
    America_Thule = 'America/Thule'
    America_Thunder_Bay = 'America/Thunder_Bay'
    America_Tijuana = 'America/Tijuana'
    America_Toronto = 'America/Toronto'
    America_Tortola = 'America/Tortola'
    America_Vancouver = 'America/Vancouver'
    America_Virgin = 'America/Virgin'
    America_Whitehorse = 'America/Whitehorse'
    America_Winnipeg = 'America/Winnipeg'
    America_Yakutat = 'America/Yakutat'
    America_Yellowknife = 'America/Yellowknife'
    Antarctica_Casey = 'Antarctica/Casey'
    Antarctica_Davis = 'Antarctica/Davis'
    Antarctica_DumontDUrville = 'Antarctica/DumontDUrville'
    Antarctica_Macquarie = 'Antarctica/Macquarie'
    Antarctica_Mawson = 'Antarctica/Mawson'
    Antarctica_McMurdo = 'Antarctica/McMurdo'
    Antarctica_Palmer = 'Antarctica/Palmer'
    Antarctica_Rothera = 'Antarctica/Rothera'
    Antarctica_South_Pole = 'Antarctica/South_Pole'
    Antarctica_Syowa = 'Antarctica/Syowa'
    Antarctica_Troll = 'Antarctica/Troll'
    Antarctica_Vostok = 'Antarctica/Vostok'
    Arctic_Longyearbyen = 'Arctic/Longyearbyen'
    Asia_Aden = 'Asia/Aden'
    Asia_Almaty = 'Asia/Almaty'
    Asia_Amman = 'Asia/Amman'
    Asia_Anadyr = 'Asia/Anadyr'
    Asia_Aqtau = 'Asia/Aqtau'
    Asia_Aqtobe = 'Asia/Aqtobe'
    Asia_Ashgabat = 'Asia/Ashgabat'
    Asia_Ashkhabad = 'Asia/Ashkhabad'
    Asia_Atyrau = 'Asia/Atyrau'
    Asia_Baghdad = 'Asia/Baghdad'
    Asia_Bahrain = 'Asia/Bahrain'
    Asia_Baku = 'Asia/Baku'
    Asia_Bangkok = 'Asia/Bangkok'
    Asia_Barnaul = 'Asia/Barnaul'
    Asia_Beirut = 'Asia/Beirut'
    Asia_Bishkek = 'Asia/Bishkek'
    Asia_Brunei = 'Asia/Brunei'
    Asia_Calcutta = 'Asia/Calcutta'
    Asia_Chita = 'Asia/Chita'
    Asia_Choibalsan = 'Asia/Choibalsan'
    Asia_Chongqing = 'Asia/Chongqing'
    Asia_Chungking = 'Asia/Chungking'
    Asia_Colombo = 'Asia/Colombo'
    Asia_Dacca = 'Asia/Dacca'
    Asia_Damascus = 'Asia/Damascus'
    Asia_Dhaka = 'Asia/Dhaka'
    Asia_Dili = 'Asia/Dili'
    Asia_Dubai = 'Asia/Dubai'
    Asia_Dushanbe = 'Asia/Dushanbe'
    Asia_Famagusta = 'Asia/Famagusta'
    Asia_Gaza = 'Asia/Gaza'
    Asia_Harbin = 'Asia/Harbin'
    Asia_Hebron = 'Asia/Hebron'
    Asia_Ho_Chi_Minh = 'Asia/Ho_Chi_Minh'
    Asia_Hong_Kong = 'Asia/Hong_Kong'
    Asia_Hovd = 'Asia/Hovd'
    Asia_Irkutsk = 'Asia/Irkutsk'
    Asia_Istanbul = 'Asia/Istanbul'
    Asia_Jakarta = 'Asia/Jakarta'
    Asia_Jayapura = 'Asia/Jayapura'
    Asia_Jerusalem = 'Asia/Jerusalem'
    Asia_Kabul = 'Asia/Kabul'
    Asia_Kamchatka = 'Asia/Kamchatka'
    Asia_Karachi = 'Asia/Karachi'
    Asia_Kashgar = 'Asia/Kashgar'
    Asia_Kathmandu = 'Asia/Kathmandu'
    Asia_Katmandu = 'Asia/Katmandu'
    Asia_Khandyga = 'Asia/Khandyga'
    Asia_Kolkata = 'Asia/Kolkata'
    Asia_Krasnoyarsk = 'Asia/Krasnoyarsk'
    Asia_Kuala_Lumpur = 'Asia/Kuala_Lumpur'
    Asia_Kuching = 'Asia/Kuching'
    Asia_Kuwait = 'Asia/Kuwait'
    Asia_Macao = 'Asia/Macao'
    Asia_Macau = 'Asia/Macau'
    Asia_Magadan = 'Asia/Magadan'
    Asia_Makassar = 'Asia/Makassar'
    Asia_Manila = 'Asia/Manila'
    Asia_Muscat = 'Asia/Muscat'
    Asia_Nicosia = 'Asia/Nicosia'
    Asia_Novokuznetsk = 'Asia/Novokuznetsk'
    Asia_Novosibirsk = 'Asia/Novosibirsk'
    Asia_Omsk = 'Asia/Omsk'
    Asia_Oral = 'Asia/Oral'
    Asia_Phnom_Penh = 'Asia/Phnom_Penh'
    Asia_Pontianak = 'Asia/Pontianak'
    Asia_Pyongyang = 'Asia/Pyongyang'
    Asia_Qatar = 'Asia/Qatar'
    Asia_Qostanay = 'Asia/Qostanay'
    Asia_Qyzylorda = 'Asia/Qyzylorda'
    Asia_Rangoon = 'Asia/Rangoon'
    Asia_Riyadh = 'Asia/Riyadh'
    Asia_Saigon = 'Asia/Saigon'
    Asia_Sakhalin = 'Asia/Sakhalin'
    Asia_Samarkand = 'Asia/Samarkand'
    Asia_Seoul = 'Asia/Seoul'
    Asia_Shanghai = 'Asia/Shanghai'
    Asia_Singapore = 'Asia/Singapore'
    Asia_Srednekolymsk = 'Asia/Srednekolymsk'
    Asia_Taipei = 'Asia/Taipei'
    Asia_Tashkent = 'Asia/Tashkent'
    Asia_Tbilisi = 'Asia/Tbilisi'
    Asia_Tehran = 'Asia/Tehran'
    Asia_Tel_Aviv = 'Asia/Tel_Aviv'
    Asia_Thimbu = 'Asia/Thimbu'
    Asia_Thimphu = 'Asia/Thimphu'
    Asia_Tokyo = 'Asia/Tokyo'
    Asia_Tomsk = 'Asia/Tomsk'
    Asia_Ujung_Pandang = 'Asia/Ujung_Pandang'
    Asia_Ulaanbaatar = 'Asia/Ulaanbaatar'
    Asia_Ulan_Bator = 'Asia/Ulan_Bator'
    Asia_Urumqi = 'Asia/Urumqi'
    Asia_Ust_Nera = 'Asia/Ust-Nera'
    Asia_Vientiane = 'Asia/Vientiane'
    Asia_Vladivostok = 'Asia/Vladivostok'
    Asia_Yakutsk = 'Asia/Yakutsk'
    Asia_Yangon = 'Asia/Yangon'
    Asia_Yekaterinburg = 'Asia/Yekaterinburg'
    Asia_Yerevan = 'Asia/Yerevan'
    Atlantic_Azores = 'Atlantic/Azores'
    Atlantic_Bermuda = 'Atlantic/Bermuda'
    Atlantic_Canary = 'Atlantic/Canary'
    Atlantic_Cape_Verde = 'Atlantic/Cape_Verde'
    Atlantic_Faeroe = 'Atlantic/Faeroe'
    Atlantic_Faroe = 'Atlantic/Faroe'
    Atlantic_Jan_Mayen = 'Atlantic/Jan_Mayen'
    Atlantic_Madeira = 'Atlantic/Madeira'
    Atlantic_Reykjavik = 'Atlantic/Reykjavik'
    Atlantic_South_Georgia = 'Atlantic/South_Georgia'
    Atlantic_St_Helena = 'Atlantic/St_Helena'
    Atlantic_Stanley = 'Atlantic/Stanley'
    Australia_ACT = 'Australia/ACT'
    Australia_Adelaide = 'Australia/Adelaide'
    Australia_Brisbane = 'Australia/Brisbane'
    Australia_Broken_Hill = 'Australia/Broken_Hill'
    Australia_Canberra = 'Australia/Canberra'
    Australia_Currie = 'Australia/Currie'
    Australia_Darwin = 'Australia/Darwin'
    Australia_Eucla = 'Australia/Eucla'
    Australia_Hobart = 'Australia/Hobart'
    Australia_LHI = 'Australia/LHI'
    Australia_Lindeman = 'Australia/Lindeman'
    Australia_Lord_Howe = 'Australia/Lord_Howe'
    Australia_Melbourne = 'Australia/Melbourne'
    Australia_NSW = 'Australia/NSW'
    Australia_North = 'Australia/North'
    Australia_Perth = 'Australia/Perth'
    Australia_Queensland = 'Australia/Queensland'
    Australia_South = 'Australia/South'
    Australia_Sydney = 'Australia/Sydney'
    Australia_Tasmania = 'Australia/Tasmania'
    Australia_Victoria = 'Australia/Victoria'
    Australia_West = 'Australia/West'
    Australia_Yancowinna = 'Australia/Yancowinna'
    Brazil_Acre = 'Brazil/Acre'
    Brazil_DeNoronha = 'Brazil/DeNoronha'
    Brazil_East = 'Brazil/East'
    Brazil_West = 'Brazil/West'
    CET = 'CET'
    CST6CDT = 'CST6CDT'
    Canada_Atlantic = 'Canada/Atlantic'
    Canada_Central = 'Canada/Central'
    Canada_Eastern = 'Canada/Eastern'
    Canada_Mountain = 'Canada/Mountain'
    Canada_Newfoundland = 'Canada/Newfoundland'
    Canada_Pacific = 'Canada/Pacific'
    Canada_Saskatchewan = 'Canada/Saskatchewan'
    Canada_Yukon = 'Canada/Yukon'
    Chile_Continental = 'Chile/Continental'
    Chile_EasterIsland = 'Chile/EasterIsland'
    Cuba = 'Cuba'
    EET = 'EET'
    EST = 'EST'
    EST5EDT = 'EST5EDT'
    Egypt = 'Egypt'
    Eire = 'Eire'
    Etc_GMT = 'Etc/GMT'
    Etc_GMT_0 = 'Etc/GMT+0'
    Etc_GMT_1 = 'Etc/GMT+1'
    Etc_GMT_10 = 'Etc/GMT+10'
    Etc_GMT_11 = 'Etc/GMT+11'
    Etc_GMT_12 = 'Etc/GMT+12'
    Etc_GMT_2 = 'Etc/GMT+2'
    Etc_GMT_3 = 'Etc/GMT+3'
    Etc_GMT_4 = 'Etc/GMT+4'
    Etc_GMT_5 = 'Etc/GMT+5'
    Etc_GMT_6 = 'Etc/GMT+6'
    Etc_GMT_7 = 'Etc/GMT+7'
    Etc_GMT_8 = 'Etc/GMT+8'
    Etc_GMT_9 = 'Etc/GMT+9'
    Etc_GMT_0_1 = 'Etc/GMT-0'
    Etc_GMT_1_1 = 'Etc/GMT-1'
    Etc_GMT_10_1 = 'Etc/GMT-10'
    Etc_GMT_11_1 = 'Etc/GMT-11'
    Etc_GMT_12_1 = 'Etc/GMT-12'
    Etc_GMT_13 = 'Etc/GMT-13'
    Etc_GMT_14 = 'Etc/GMT-14'
    Etc_GMT_2_1 = 'Etc/GMT-2'
    Etc_GMT_3_1 = 'Etc/GMT-3'
    Etc_GMT_4_1 = 'Etc/GMT-4'
    Etc_GMT_5_1 = 'Etc/GMT-5'
    Etc_GMT_6_1 = 'Etc/GMT-6'
    Etc_GMT_7_1 = 'Etc/GMT-7'
    Etc_GMT_8_1 = 'Etc/GMT-8'
    Etc_GMT_9_1 = 'Etc/GMT-9'
    Etc_GMT0 = 'Etc/GMT0'
    Etc_Greenwich = 'Etc/Greenwich'
    Etc_UCT = 'Etc/UCT'
    Etc_UTC = 'Etc/UTC'
    Etc_Universal = 'Etc/Universal'
    Etc_Zulu = 'Etc/Zulu'
    Europe_Amsterdam = 'Europe/Amsterdam'
    Europe_Andorra = 'Europe/Andorra'
    Europe_Astrakhan = 'Europe/Astrakhan'
    Europe_Athens = 'Europe/Athens'
    Europe_Belfast = 'Europe/Belfast'
    Europe_Belgrade = 'Europe/Belgrade'
    Europe_Berlin = 'Europe/Berlin'
    Europe_Bratislava = 'Europe/Bratislava'
    Europe_Brussels = 'Europe/Brussels'
    Europe_Bucharest = 'Europe/Bucharest'
    Europe_Budapest = 'Europe/Budapest'
    Europe_Busingen = 'Europe/Busingen'
    Europe_Chisinau = 'Europe/Chisinau'
    Europe_Copenhagen = 'Europe/Copenhagen'
    Europe_Dublin = 'Europe/Dublin'
    Europe_Gibraltar = 'Europe/Gibraltar'
    Europe_Guernsey = 'Europe/Guernsey'
    Europe_Helsinki = 'Europe/Helsinki'
    Europe_Isle_of_Man = 'Europe/Isle_of_Man'
    Europe_Istanbul = 'Europe/Istanbul'
    Europe_Jersey = 'Europe/Jersey'
    Europe_Kaliningrad = 'Europe/Kaliningrad'
    Europe_Kiev = 'Europe/Kiev'
    Europe_Kirov = 'Europe/Kirov'
    Europe_Kyiv = 'Europe/Kyiv'
    Europe_Lisbon = 'Europe/Lisbon'
    Europe_Ljubljana = 'Europe/Ljubljana'
    Europe_London = 'Europe/London'
    Europe_Luxembourg = 'Europe/Luxembourg'
    Europe_Madrid = 'Europe/Madrid'
    Europe_Malta = 'Europe/Malta'
    Europe_Mariehamn = 'Europe/Mariehamn'
    Europe_Minsk = 'Europe/Minsk'
    Europe_Monaco = 'Europe/Monaco'
    Europe_Moscow = 'Europe/Moscow'
    Europe_Nicosia = 'Europe/Nicosia'
    Europe_Oslo = 'Europe/Oslo'
    Europe_Paris = 'Europe/Paris'
    Europe_Podgorica = 'Europe/Podgorica'
    Europe_Prague = 'Europe/Prague'
    Europe_Riga = 'Europe/Riga'
    Europe_Rome = 'Europe/Rome'
    Europe_Samara = 'Europe/Samara'
    Europe_San_Marino = 'Europe/San_Marino'
    Europe_Sarajevo = 'Europe/Sarajevo'
    Europe_Saratov = 'Europe/Saratov'
    Europe_Simferopol = 'Europe/Simferopol'
    Europe_Skopje = 'Europe/Skopje'
    Europe_Sofia = 'Europe/Sofia'
    Europe_Stockholm = 'Europe/Stockholm'
    Europe_Tallinn = 'Europe/Tallinn'
    Europe_Tirane = 'Europe/Tirane'
    Europe_Tiraspol = 'Europe/Tiraspol'
    Europe_Ulyanovsk = 'Europe/Ulyanovsk'
    Europe_Uzhgorod = 'Europe/Uzhgorod'
    Europe_Vaduz = 'Europe/Vaduz'
    Europe_Vatican = 'Europe/Vatican'
    Europe_Vienna = 'Europe/Vienna'
    Europe_Vilnius = 'Europe/Vilnius'
    Europe_Volgograd = 'Europe/Volgograd'
    Europe_Warsaw = 'Europe/Warsaw'
    Europe_Zagreb = 'Europe/Zagreb'
    Europe_Zaporozhye = 'Europe/Zaporozhye'
    Europe_Zurich = 'Europe/Zurich'
    Factory = 'Factory'
    GB = 'GB'
    GB_Eire = 'GB-Eire'
    GMT = 'GMT'
    GMT_0 = 'GMT+0'
    GMT_0_1 = 'GMT-0'
    GMT0 = 'GMT0'
    Greenwich = 'Greenwich'
    HST = 'HST'
    Hongkong = 'Hongkong'
    Iceland = 'Iceland'
    Indian_Antananarivo = 'Indian/Antananarivo'
    Indian_Chagos = 'Indian/Chagos'
    Indian_Christmas = 'Indian/Christmas'
    Indian_Cocos = 'Indian/Cocos'
    Indian_Comoro = 'Indian/Comoro'
    Indian_Kerguelen = 'Indian/Kerguelen'
    Indian_Mahe = 'Indian/Mahe'
    Indian_Maldives = 'Indian/Maldives'
    Indian_Mauritius = 'Indian/Mauritius'
    Indian_Mayotte = 'Indian/Mayotte'
    Indian_Reunion = 'Indian/Reunion'
    Iran = 'Iran'
    Israel = 'Israel'
    Jamaica = 'Jamaica'
    Japan = 'Japan'
    Kwajalein = 'Kwajalein'
    Libya = 'Libya'
    MET = 'MET'
    MST = 'MST'
    MST7MDT = 'MST7MDT'
    Mexico_BajaNorte = 'Mexico/BajaNorte'
    Mexico_BajaSur = 'Mexico/BajaSur'
    Mexico_General = 'Mexico/General'
    NZ = 'NZ'
    NZ_CHAT = 'NZ-CHAT'
    Navajo = 'Navajo'
    PRC = 'PRC'
    PST8PDT = 'PST8PDT'
    Pacific_Apia = 'Pacific/Apia'
    Pacific_Auckland = 'Pacific/Auckland'
    Pacific_Bougainville = 'Pacific/Bougainville'
    Pacific_Chatham = 'Pacific/Chatham'
    Pacific_Chuuk = 'Pacific/Chuuk'
    Pacific_Easter = 'Pacific/Easter'
    Pacific_Efate = 'Pacific/Efate'
    Pacific_Enderbury = 'Pacific/Enderbury'
    Pacific_Fakaofo = 'Pacific/Fakaofo'
    Pacific_Fiji = 'Pacific/Fiji'
    Pacific_Funafuti = 'Pacific/Funafuti'
    Pacific_Galapagos = 'Pacific/Galapagos'
    Pacific_Gambier = 'Pacific/Gambier'
    Pacific_Guadalcanal = 'Pacific/Guadalcanal'
    Pacific_Guam = 'Pacific/Guam'
    Pacific_Honolulu = 'Pacific/Honolulu'
    Pacific_Johnston = 'Pacific/Johnston'
    Pacific_Kanton = 'Pacific/Kanton'
    Pacific_Kiritimati = 'Pacific/Kiritimati'
    Pacific_Kosrae = 'Pacific/Kosrae'
    Pacific_Kwajalein = 'Pacific/Kwajalein'
    Pacific_Majuro = 'Pacific/Majuro'
    Pacific_Marquesas = 'Pacific/Marquesas'
    Pacific_Midway = 'Pacific/Midway'
    Pacific_Nauru = 'Pacific/Nauru'
    Pacific_Niue = 'Pacific/Niue'
    Pacific_Norfolk = 'Pacific/Norfolk'
    Pacific_Noumea = 'Pacific/Noumea'
    Pacific_Pago_Pago = 'Pacific/Pago_Pago'
    Pacific_Palau = 'Pacific/Palau'
    Pacific_Pitcairn = 'Pacific/Pitcairn'
    Pacific_Pohnpei = 'Pacific/Pohnpei'
    Pacific_Ponape = 'Pacific/Ponape'
    Pacific_Port_Moresby = 'Pacific/Port_Moresby'
    Pacific_Rarotonga = 'Pacific/Rarotonga'
    Pacific_Saipan = 'Pacific/Saipan'
    Pacific_Samoa = 'Pacific/Samoa'
    Pacific_Tahiti = 'Pacific/Tahiti'
    Pacific_Tarawa = 'Pacific/Tarawa'
    Pacific_Tongatapu = 'Pacific/Tongatapu'
    Pacific_Truk = 'Pacific/Truk'
    Pacific_Wake = 'Pacific/Wake'
    Pacific_Wallis = 'Pacific/Wallis'
    Pacific_Yap = 'Pacific/Yap'
    Poland = 'Poland'
    Portugal = 'Portugal'
    ROC = 'ROC'
    ROK = 'ROK'
    Singapore = 'Singapore'
    Turkey = 'Turkey'
    UCT = 'UCT'
    US_Alaska = 'US/Alaska'
    US_Aleutian = 'US/Aleutian'
    US_Arizona = 'US/Arizona'
    US_Central = 'US/Central'
    US_East_Indiana = 'US/East-Indiana'
    US_Eastern = 'US/Eastern'
    US_Hawaii = 'US/Hawaii'
    US_Indiana_Starke = 'US/Indiana-Starke'
    US_Michigan = 'US/Michigan'
    US_Mountain = 'US/Mountain'
    US_Pacific = 'US/Pacific'
    US_Samoa = 'US/Samoa'
    UTC = 'UTC'
    Universal = 'Universal'
    W_SU = 'W-SU'
    WET = 'WET'
    Zulu = 'Zulu'
    localtime = 'localtime'


class BodyLoginPostLoginPost(BaseModel):
    email: EmailStr = Field(..., title='Email')
    tz: Tz | None = Field('Europe/Oslo', title='Tz')
    state: str | None = Field(None, title='State')


class BodyPostCreateManagedUserSettingsManagedUsersPost(BaseModel):
    first_name: str = Field(..., title='First Name')
    last_name: str | None = Field(None, title='Last Name')


class BodyPublishSubmitApplicationsApplicationIdPublishPost(BaseModel):
    description: str = Field(..., title='Description')
    url: str | None = Field(None, title='Url')
    image: str | None = Field(None, title='Image')
    privacy_statement: str | None = Field(None, title='Privacy Statement')
    fast_track: bool | None = Field(False, title='Fast Track')
    publish_to_directory: bool | None = Field(False, title='Publish To Directory')


class BodyPutUpdateManagedUserSettingsManagedUsersUserIdPut(BaseModel):
    first_name: str = Field(..., title='First Name')
    last_name: str | None = Field(None, title='Last Name')


class BodyResendMagicLinkPartialsResendMagicLinkPost(BaseModel):
    email: EmailStr = Field(..., title='Email')
    tz: Tz | None = Field('Europe/Oslo', title='Tz')


class BodySaveOrUpdateIntegrationProviderTenantsTenantIdIntegrationProvidersIntegrationNamePost(
    BaseModel
):
    client_id: str = Field(..., title='Client Id')
    client_secret: SecretStr = Field(..., title='Client Secret')
    redirect_url: str = Field(..., title='Redirect Url')


class BodyUpdateManagedUserApiV1UsersUserIdPut(BaseModel):
    first_name: str | None = Field(None, title='First Name')
    last_name: str | None = Field(None, title='Last Name')


class BodyUpdateUserUsersUserIdPut(BaseModel):
    first_name: str = Field(..., title='First Name')
    last_name: str = Field(..., title='Last Name')


class BodyUploadActivityFileDataUploadPost(BaseModel):
    files: list[bytes] = Field(..., title='Files')


class CadenceSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    max: float | None = Field(None, title='Max')


class CoreTemperatureSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    min: float | None = Field(None, title='Min')
    max: float | None = Field(None, title='Max')
    start: float | None = Field(None, title='Start')
    end: float | None = Field(None, title='End')


class DailyCreate(BaseModel):
    date: date_aliased = Field(..., title='Date')
    value: float = Field(..., title='Value')


class DailyMeasure(Enum):
    body_mass = 'body_mass'
    body_fat_pct = 'body_fat_pct'
    resting_hr = 'resting_hr'
    hrv = 'hrv'
    sleep_duration = 'sleep_duration'
    sleep_altitude = 'sleep_altitude'
    menstrual_cycle_day = 'menstrual_cycle_day'


class DailyResponse(BaseModel):
    date: date_aliased = Field(..., title='Date')
    value: float | None = Field(..., title='Value')
    source: str = Field(..., title='Source')


class DistanceSummary(BaseModel):
    sum: int | float | None = Field(None, title='Sum')


class GarminBackfillBody(BaseModel):
    start: AwareDatetime = Field(..., title='Start')
    end: AwareDatetime = Field(..., title='End')
    user_id__in: list[str] | None = Field(None, title='User Id  In')
    user_id__not_in: list[str] | None = Field(None, title='User Id  Not In')


class GarminConnectUserPermission(Enum):
    HISTORICAL_DATA_EXPORT = 'HISTORICAL_DATA_EXPORT'
    ACTIVITY_EXPORT = 'ACTIVITY_EXPORT'


class GarminDeregistration(BaseModel):
    userId: str = Field(..., title='Userid')
    userAccessToken: str = Field(..., title='Useraccesstoken')


class GarminDeregistrationBody(BaseModel):
    deregistrations: list[GarminDeregistration] = Field(..., title='Deregistrations')


class GarminFileTypes(Enum):
    FIT = 'FIT'
    GPX = 'GPX'
    TCX = 'TCX'


class GarminUserPermissionChange(BaseModel):
    userId: str = Field(..., title='Userid')
    userAccessToken: str = Field(..., title='Useraccesstoken')
    permissions: list[GarminConnectUserPermission] = Field(..., title='Permissions')


class GarminUserPermissionsBody(BaseModel):
    userPermissionsChange: list[GarminUserPermissionChange] = Field(
        ..., title='Userpermissionschange'
    )


class GrantType(Enum):
    authorization_code = 'authorization_code'
    refresh_token = 'refresh_token'


class HeartRateSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    min: float | None = Field(None, title='Min')
    max: float | None = Field(None, title='Max')
    start: float | None = Field(None, title='Start')
    end: float | None = Field(None, title='End')


class Instruction(BaseModel):
    type: Literal['instruction'] = Field('instruction', title='Type')
    text: str = Field(..., title='Text')


class IntegrationName(Enum):
    garmin_connect = 'garmin_connect'
    intervals_icu = 'intervals_icu'


class IntensityQuantity(Enum):
    speed = 'speed'
    power = 'power'


class IntervalsIcuWebhookEventType(Enum):
    APP_SCOPE_CHANGED = 'APP_SCOPE_CHANGED'
    CALENDAR_UPDATED = 'CALENDAR_UPDATED'
    CALENDAR_EVENT_UPDATED = 'CALENDAR_EVENT_UPDATED'
    CALENDAR_EVENT_DELETED = 'CALENDAR_EVENT_DELETED'
    ACTIVITY_UPLOADED = 'ACTIVITY_UPLOADED'
    ACTIVITY_ANALYZED = 'ACTIVITY_ANALYZED'
    ACTIVITY_UPDATED = 'ACTIVITY_UPDATED'
    ACTIVITY_DELETED = 'ACTIVITY_DELETED'
    ACTIVITY_ACHIEVEMENTS = 'ACTIVITY_ACHIEVEMENTS'
    WELLNESS_UPDATED = 'WELLNESS_UPDATED'
    FITNESS_UPDATED = 'FITNESS_UPDATED'


class ManagedUserCreate(BaseModel):
    first_name: str = Field(..., title='First Name')
    last_name: str | None = Field(..., title='Last Name')


class Marker(BaseModel):
    power: int | None = Field(None, title='Power')
    speed: float | None = Field(None, title='Speed')
    heart_rate: int | None = Field(None, title='Heart Rate')
    lactate: float | None = Field(None, title='Lactate')
    vo2: float | None = Field(None, title='Vo2')


class MetabolicMapResponse(BaseModel):
    fatmax: float = Field(..., title='Fatmax')
    mlss: float = Field(..., title='Mlss')
    cp: float = Field(..., title='Cp')
    vo2max: float = Field(..., title='Vo2Max')
    vo2max_intensity: float = Field(..., title='Vo2Max Intensity')


class Metric(Enum):
    duration = 'duration'
    lap = 'lap'
    power = 'power'
    speed = 'speed'
    heart_rate = 'heart_rate'
    respiration_rate = 'respiration_rate'
    smo2 = 'smo2'
    core_temperature = 'core_temperature'
    elevation = 'elevation'
    altitude = 'altitude'
    cadence = 'cadence'
    temperature = 'temperature'
    distance = 'distance'
    longitude = 'longitude'
    latitude = 'latitude'
    lactate = 'lactate'
    rpe = 'rpe'
    notes = 'notes'


class PageApplicationInfo(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    is_private: bool = Field(..., title='Is Private')


class PageResponse(BaseModel):
    slug: str = Field(..., title='Slug')
    published: bool = Field(..., title='Published')
    application: PageApplicationInfo
    url: str = Field(
        ..., description='The public URL where this page is served.', title='Url'
    )


class PowerSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    max: float | None = Field(None, title='Max')


class Reference(Enum):
    absolute = 'absolute'
    tte = 'tte'
    parameter = 'parameter'


class RepeatQuantity(Enum):
    number = 'number'


class Scope(Enum):
    data_read = 'data:read'
    data_write = 'data:write'
    admin = 'admin'
    openid = 'openid'
    profile = 'profile'
    offline_access = 'offline_access'


class Smo2Summary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    min: float | None = Field(None, title='Min')
    max: float | None = Field(None, title='Max')
    start: float | None = Field(None, title='Start')
    end: float | None = Field(None, title='End')


class SpeedSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    max: float | None = Field(None, title='Max')


from open_sport_taxonomy.pydantic import SportField as Sport  # OST sport type (see schemas.py)


class SubscriptionPlan(Enum):
    free = 'free'
    early_access = 'early_access'
    individual = 'individual'
    developer = 'developer'
    team = 'team'


class TeamCreateOrUpdate(BaseModel):
    name: str = Field(..., title='Name')
    description: str = Field(..., title='Description')
    url: AnyUrl = Field(..., title='Url')
    image: AnyUrl = Field(..., title='Image')
    privacy_statement: AnyUrl = Field(..., title='Privacy Statement')


class TeamResponse(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str = Field(..., title='Description')
    url: AnyUrl = Field(..., title='Url')
    image: AnyUrl = Field(..., title='Image')
    privacy_statement: AnyUrl = Field(..., title='Privacy Statement')
    role: ApplicationMemberRole | None


class TemperatureSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    min: float | None = Field(None, title='Min')
    max: float | None = Field(None, title='Max')
    start: float | None = Field(None, title='Start')
    end: float | None = Field(None, title='End')


class TemplateDay(BaseModel):
    sports: list[Sport] = Field(..., title='Sports')
    avg_training_duration: timedelta = Field(..., title='Avg Training Duration')
    typical_training_duration: timedelta = Field(..., title='Typical Training Duration')


class TemplateWeekResponse(BaseModel):
    monday: TemplateDay
    tuesday: TemplateDay
    wednesday: TemplateDay
    thursday: TemplateDay
    friday: TemplateDay
    saturday: TemplateDay
    sunday: TemplateDay


class TestResults(BaseModel):
    first_threshold: Marker | None = None
    second_threshold: Marker | None = None
    fatmax: Marker | None = None
    lt1: Marker | None = None
    lt2: Marker | None = None
    vt1: Marker | None = None
    vt2: Marker | None = None
    mlss: Marker | None = None
    vo2max: float | None = Field(None, title='Vo2Max')
    vo2peak: float | None = Field(None, title='Vo2Peak')
    vlamax: float | None = Field(None, title='Vlamax')
    heart_rate_max: int | None = Field(None, title='Heart Rate Max')
    critical_power: int | None = Field(None, title='Critical Power')
    critical_speed: float | None = Field(None, title='Critical Speed')
    w_prime: float | None = Field(None, title='W Prime')
    d_prime: float | None = Field(None, title='D Prime')
    economy: float | None = Field(None, title='Economy')
    efficiency: float | None = Field(None, title='Efficiency')


class TestSummary(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    created_by: str | None = Field(None, title='Created By')
    title: str | None = Field(None, title='Title')
    sport: Sport
    start: AwareDatetime = Field(..., title='Start')
    end: AwareDatetime | None = Field(None, title='End')
    results: TestResults | None = None
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    start_local: NaiveDatetime = Field(..., title='Start Local')
    end_local: NaiveDatetime | None = Field(..., title='End Local')


class TestUpdate(BaseModel):
    title: str | None = Field(None, title='Title')
    sport: Sport
    start: AwareDatetime = Field(..., title='Start')
    end: AwareDatetime | None = Field(None, title='End')
    results: TestResults | None = None
    tags: list[str] | None = Field(None, title='Tags')


class TokenRequest(BaseModel):
    grant_type: GrantType
    client_id: str | None = Field(None, title='Client Id')
    code: str | None = Field(None, title='Code')
    client_secret: str | None = Field(None, title='Client Secret')
    code_verifier: str | None = Field(None, title='Code Verifier')
    refresh_token: str | None = Field(None, title='Refresh Token')
    tz: Tz | None = Field('Europe/Oslo', title='Tz')


class TokenResponse(BaseModel):
    access_token: str = Field(..., title='Access Token')
    token_type: Literal['Bearer'] = Field('Bearer', title='Token Type')
    expires_in: int = Field(..., title='Expires In')
    refresh_token: str | None = Field(None, title='Refresh Token')
    scope: str | None = Field(None, title='Scope')
    id_token: str | None = Field(None, title='Id Token')


class TraceCreateOrUpdate(BaseModel):
    timestamp: AwareDatetime = Field(..., title='Timestamp')
    test_id: str | None = Field(None, title='Test Id')
    lactate: float | None = Field(None, title='Lactate')
    rpe: int | None = Field(None, title='Rpe')
    notes: str | None = Field(None, title='Notes')
    power: conint(ge=0) | None = Field(None, title='Power')
    speed: confloat(ge=0.0) | None = Field(None, title='Speed')
    heart_rate: conint(ge=0) | None = Field(None, title='Heart Rate')
    vo2: confloat(ge=0.0) | None = Field(None, title='Vo2')
    tags: list[str] | None = Field(None, title='Tags')
    sport: Sport | None = None


class TraceResolution(Enum):
    auto = 'auto'
    linked = 'linked'


class UserFlow(Enum):
    session = 'session'
    signup = 'signup'
    login = 'login'


class UserInfoResponse(BaseModel):
    sub: str = Field(..., title='Sub')
    given_name: str | None = Field(None, title='Given Name')
    family_name: str | None = Field(None, title='Family Name')
    email: str | None = Field(None, title='Email')
    registered_at: AwareDatetime | NaiveDatetime = Field(..., title='Registered At')
    name: str = Field(..., title='Name')


class UserResponse(BaseModel):
    id: str = Field(..., title='Id')
    first_name: str | None = Field(..., title='First Name')
    last_name: str | None = Field(..., title='Last Name')
    admin: bool = Field(..., title='Admin')
    registered_at: AwareDatetime | NaiveDatetime = Field(..., title='Registered At')
    display_name: str = Field(..., title='Display Name')
    is_managed: bool = Field(..., title='Is Managed')


class UserSummary(BaseModel):
    id: str = Field(..., title='Id')
    first_name: str | None = Field(..., title='First Name')
    last_name: str | None = Field(..., title='Last Name')
    scopes: list[Scope] = Field(..., title='Scopes')
    display_name: str = Field(..., title='Display Name')
    is_managed: bool = Field(..., title='Is Managed')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class Value(BaseModel):
    reference: Reference
    value: int | float = Field(..., title='Value')
    parameter: str | None = Field(None, title='Parameter')


class VolumeQuantity(Enum):
    duration = 'duration'
    distance = 'distance'


class WebhookEventType(Enum):
    activity_created = 'activity_created'
    activity_updated = 'activity_updated'
    activity_deleted = 'activity_deleted'
    test_created = 'test_created'
    test_updated = 'test_updated'
    test_deleted = 'test_deleted'


class ActivitySummarySummary(BaseModel):
    power: PowerSummary | None = None
    speed: SpeedSummary | None = None
    distance: DistanceSummary | None = None
    altitude: AltitudeSummary | None = None
    heart_rate: HeartRateSummary | None = None
    cadence: CadenceSummary | None = None
    temperature: TemperatureSummary | None = None
    core_temperature: CoreTemperatureSummary | None = None
    smo2: Smo2Summary | None = None


class ApplicationCreateResponse(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    image: AnyUrl | None = Field(None, title='Image')
    url: AnyUrl | None = Field(None, title='Url')
    redirect_uris: list[AnyUrl] | None = Field(None, title='Redirect Uris')
    privacy_statement: AnyUrl | None = Field(None, title='Privacy Statement')
    published: bool = Field(..., title='Published')
    webhook_endpoints: list[AnyUrl] | None = Field(None, title='Webhook Endpoints')
    webhook_secret: SecretStr | None = Field(None, title='Webhook Secret')
    client_secret: str | None = Field(None, title='Client Secret')
    page: PageResponse | None = None
    is_private: bool = Field(
        ...,
        description='An application is private if it is missing any of: description, URL, image, or privacy statement.',
        title='Is Private',
    )
    is_clientside_app: bool = Field(
        ...,
        description='Check if this is a client-side app based on privacy policy URL.\n\nApps published via fast-track have privacy_statement set to the standard\nclient-side privacy policy URL, indicating they attested to being client-side.',
        title='Is Clientside App',
    )


class AuthorizeQueryParams(BaseModel):
    client_id: str = Field(..., title='Client Id')
    redirect_uri: str | None = Field(None, title='Redirect Uri')
    scope: list[Scope] = Field(..., min_length=1, title='Scope')
    state: str | None = Field(None, title='State')
    nonce: str | None = Field(None, title='Nonce')
    code_challenge: str | None = Field(None, title='Code Challenge')
    code_challenge_method: str | None = Field(None, title='Code Challenge Method')
    prompt: Prompt | None = Field('consent', title='Prompt')
    user_flow: UserFlow | None = 'session'


class AuthorizeTeamRequest(BaseModel):
    scopes: list[Scope] = Field(..., title='Scopes')


class AuthorizedTeamResponse(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str = Field(..., title='Description')
    url: AnyUrl = Field(..., title='Url')
    image: AnyUrl = Field(..., title='Image')
    privacy_statement: AnyUrl = Field(..., title='Privacy Statement')
    scopes: list[Scope] = Field(..., title='Scopes')


class BodyAuthorizeOauthAuthorizePost(BaseModel):
    client_id: str = Field(..., title='Client Id')
    redirect_uri: str | None = Field(None, title='Redirect Uri')
    scopes: list[Scope] = Field(..., min_length=1, title='Scopes')
    state: str | None = Field(None, title='State')
    nonce: str | None = Field(None, title='Nonce')
    code_challenge: str | None = Field(None, title='Code Challenge')
    code_challenge_method: str | None = Field(None, title='Code Challenge Method')


class BodyCreateCheckoutSessionApiV1PaymentStripeCheckoutPost(BaseModel):
    subscription_plan: SubscriptionPlan


class BodyCreateDailyDataDailiesPost(BaseModel):
    measure: DailyMeasure
    date: date_aliased = Field(..., title='Date')
    value: float = Field(..., title='Value')


class BodyExpressAddEmailPostExpressAddEmailPost(BaseModel):
    email: EmailStr = Field(..., title='Email')
    state: str | None = Field(None, title='State')
    user_flow: UserFlow | None = 'session'


class BodyGenerateApiKeyPartialsGenerateApiKeyPost(BaseModel):
    scopes: list[Scope] = Field(..., title='Scopes')


class BodyUploadActivityFileApiV1ActivitiesUploadPost(BaseModel):
    files: list[bytes] = Field(..., max_length=10, title='Files')
    sport: Sport | None = None


class ConstantValueInput(BaseModel):
    type: Literal['constant'] = Field('constant', title='Type')
    quantity: VolumeQuantity | IntensityQuantity | RepeatQuantity = Field(
        ..., title='Quantity'
    )
    value: Value


class ConstantValueOutput(BaseModel):
    type: Literal['constant'] = Field('constant', title='Type')
    quantity: VolumeQuantity | IntensityQuantity | RepeatQuantity = Field(
        ..., title='Quantity'
    )
    value: Value


class DelegatedTokenRequest(BaseModel):
    sub: str = Field(..., title='Sub')
    scopes: list[Scope] | None = Field(None, title='Scopes')
    team_id: str | None = Field(None, title='Team Id')


class GarminActivityFileData(BaseModel):
    userId: str = Field(..., title='Userid')
    userAccessToken: str = Field(..., title='Useraccesstoken')
    summaryId: str = Field(..., title='Summaryid')
    fileType: GarminFileTypes
    callbackURL: str = Field(..., title='Callbackurl')
    startTimeInSeconds: AwareDatetime = Field(..., title='Starttimeinseconds')
    activityId: str = Field(..., title='Activityid')
    activityName: str | None = Field(None, title='Activityname')
    manual: bool | None = Field(False, title='Manual')


class GarminPingBody(BaseModel):
    activityFiles: list[GarminActivityFileData] = Field(..., title='Activityfiles')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class IntervalsIcuWebhookEvent(BaseModel):
    athlete_id: str = Field(..., title='Athlete Id')
    type: IntervalsIcuWebhookEventType
    timestamp: AwareDatetime = Field(..., title='Timestamp')
    activity: Activity


class Lap(BaseModel):
    power: PowerSummary | None = None
    speed: SpeedSummary | None = None
    distance: DistanceSummary | None = None
    altitude: AltitudeSummary | None = None
    heart_rate: HeartRateSummary | None = None
    cadence: CadenceSummary | None = None
    temperature: TemperatureSummary | None = None
    core_temperature: CoreTemperatureSummary | None = None
    smo2: Smo2Summary | None = None
    start: AwareDatetime = Field(..., title='Start')
    end: AwareDatetime = Field(..., title='End')
    duration: timedelta = Field(..., title='Duration')
    start_local: NaiveDatetime = Field(..., title='Start Local')
    end_local: NaiveDatetime = Field(..., title='End Local')


class RampValueInput(BaseModel):
    type: Literal['ramp'] = Field('ramp', title='Type')
    quantity: VolumeQuantity | IntensityQuantity | RepeatQuantity = Field(
        ..., title='Quantity'
    )
    start: Value
    end: Value


class RampValueOutput(BaseModel):
    type: Literal['ramp'] = Field('ramp', title='Type')
    quantity: VolumeQuantity | IntensityQuantity | RepeatQuantity = Field(
        ..., title='Quantity'
    )
    start: Value
    end: Value


class RangeValueInput(BaseModel):
    type: Literal['range'] = Field('range', title='Type')
    quantity: VolumeQuantity | IntensityQuantity | RepeatQuantity = Field(
        ..., title='Quantity'
    )
    min: Value | None = None
    max: Value | None = None


class RangeValueOutput(BaseModel):
    type: Literal['range'] = Field('range', title='Type')
    quantity: VolumeQuantity | IntensityQuantity | RepeatQuantity = Field(
        ..., title='Quantity'
    )
    min: Value | None = None
    max: Value | None = None


class TestCreate(BaseModel):
    title: str | None = Field(None, title='Title')
    sport: Sport
    start: AwareDatetime = Field(..., title='Start')
    end: AwareDatetime | None = Field(None, title='End')
    results: TestResults | None = None
    tags: list[str] | None = Field(None, title='Tags')


class WebhookEventBody(BaseModel):
    user_id: str = Field(..., title='User Id')
    event_type: WebhookEventType
    resource_id: str | None = Field(..., title='Resource Id')
    timestamp: AwareDatetime = Field(..., title='Timestamp')


class IntervalInput(BaseModel):
    type: Literal['interval'] = Field('interval', title='Type')
    volume: ConstantValueInput | RangeValueInput | RampValueInput = Field(
        ..., discriminator='type', title='Volume'
    )
    intensity: ConstantValueInput | RangeValueInput | RampValueInput = Field(
        ..., discriminator='type', title='Intensity'
    )


class IntervalOutput(BaseModel):
    type: Literal['interval'] = Field('interval', title='Type')
    volume: ConstantValueOutput | RangeValueOutput | RampValueOutput = Field(
        ..., discriminator='type', title='Volume'
    )
    intensity: ConstantValueOutput | RangeValueOutput | RampValueOutput = Field(
        ..., discriminator='type', title='Intensity'
    )


class IntervalsIcuWebhookBody(BaseModel):
    secret: str = Field(..., title='Secret')
    events: list[IntervalsIcuWebhookEvent] = Field(..., title='Events')


class RepeatInput(BaseModel):
    type: Literal['repeat'] = Field(..., title='Type')
    count: ConstantValueInput | RangeValueInput = Field(
        ..., discriminator='type', title='Count'
    )
    content: list[IntervalInput | RepeatInput | Instruction] = Field(
        ..., title='Content'
    )


class RepeatOutput(BaseModel):
    type: Literal['repeat'] = Field(..., title='Type')
    count: ConstantValueOutput | RangeValueOutput = Field(
        ..., discriminator='type', title='Count'
    )
    content: list[IntervalOutput | RepeatOutput | Instruction] = Field(
        ..., title='Content'
    )


class SectionInput(BaseModel):
    type: Literal['section'] = Field('section', title='Type')
    name: str | None = Field(..., title='Name')
    content: list[IntervalInput | RepeatInput | Instruction] = Field(
        ..., title='Content'
    )


class SectionOutput(BaseModel):
    type: Literal['section'] = Field('section', title='Type')
    name: str | None = Field(..., title='Name')
    content: list[IntervalOutput | RepeatOutput | Instruction] = Field(
        ..., title='Content'
    )


class Content(RootModel[IntervalInput | RepeatInput | SectionInput | Instruction]):
    root: IntervalInput | RepeatInput | SectionInput | Instruction = Field(
        ..., discriminator='type'
    )


class WorkoutInput(BaseModel):
    version: str | None = Field('0.1.0', title='Version')
    title: str | None = Field(None, title='Title')
    description: str | None = Field(None, title='Description')
    content: list[Content] = Field(..., title='Content')


class Content1(RootModel[IntervalOutput | RepeatOutput | SectionOutput | Instruction]):
    root: IntervalOutput | RepeatOutput | SectionOutput | Instruction = Field(
        ..., discriminator='type'
    )


class WorkoutOutput(BaseModel):
    version: str | None = Field('0.1.0', title='Version')
    title: str | None = Field(None, title='Title')
    description: str | None = Field(None, title='Description')
    content: list[Content1] = Field(..., title='Content')


class LibraryWorkoutCreate(BaseModel):
    swf: WorkoutInput
    sport: Sport


class LibraryWorkoutResponse(BaseModel):
    id: str = Field(..., title='Id')
    swf: WorkoutOutput
    sport: Sport


class ScheduledWorkoutCreate(BaseModel):
    swf: WorkoutInput
    sport: Sport
    start: AwareDatetime = Field(..., title='Start')


class ScheduledWorkoutResponse(BaseModel):
    id: str = Field(..., title='Id')
    swf: WorkoutOutput
    sport: Sport
    start: AwareDatetime | None = Field(..., title='Start')


class ActivityDetails(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    sport: Sport
    start: AwareDatetime = Field(..., title='Start')
    end: AwareDatetime = Field(..., title='End')
    metrics: list[Metric] = Field(..., title='Metrics')
    source_id: str = Field(..., title='Source Id')
    summary: ActivitySummarySummary | None = None
    laps: list[Lap] | None = Field(None, title='Laps')
    traces: list[TraceDetails] | None = Field(None, title='Traces')
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    distance: float | None = Field(None, title='Distance')
    devices: list[str] | None = Field(None, title='Devices')
    duration: timedelta = Field(..., title='Duration')
    start_local: NaiveDatetime = Field(..., title='Start Local')
    end_local: NaiveDatetime = Field(..., title='End Local')


class ActivitySummary(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    sport: Sport
    start: AwareDatetime = Field(..., title='Start')
    end: AwareDatetime = Field(..., title='End')
    metrics: list[Metric] = Field(..., title='Metrics')
    source_id: str = Field(..., title='Source Id')
    summary: ActivitySummarySummary | None = None
    laps: list[Lap] | None = Field(None, title='Laps')
    traces: list[TraceDetails] | None = Field(None, title='Traces')
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    duration: timedelta = Field(..., title='Duration')
    start_local: NaiveDatetime = Field(..., title='Start Local')
    end_local: NaiveDatetime = Field(..., title='End Local')


class TestDetails(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    created_by: str | None = Field(None, title='Created By')
    title: str | None = Field(None, title='Title')
    sport: Sport
    start: AwareDatetime = Field(..., title='Start')
    end: AwareDatetime | None = Field(None, title='End')
    results: TestResults | None = None
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    traces: list[TraceDetails] | None = Field(None, title='Traces')
    activities: list[ActivitySummary] | None = Field(None, title='Activities')
    start_local: NaiveDatetime = Field(..., title='Start Local')
    end_local: NaiveDatetime | None = Field(..., title='End Local')


class TraceDetails(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    test_id: str | None = Field(None, title='Test Id')
    timestamp: AwareDatetime = Field(..., title='Timestamp')
    lactate: float | None = Field(None, title='Lactate')
    rpe: int | None = Field(None, title='Rpe')
    notes: str | None = Field(None, title='Notes')
    power: conint(ge=0) | None = Field(None, title='Power')
    speed: confloat(ge=0.0) | None = Field(None, title='Speed')
    heart_rate: conint(ge=0) | None = Field(None, title='Heart Rate')
    vo2: confloat(ge=0.0) | None = Field(None, title='Vo2')
    lap: Lap | None = None
    activity: ActivitySummary | None = None
    sport: Sport | None = None
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    timestamp_local: NaiveDatetime = Field(..., title='Timestamp Local')


RepeatInput.model_rebuild()
RepeatOutput.model_rebuild()
ActivityDetails.model_rebuild()
ActivitySummary.model_rebuild()
TestDetails.model_rebuild()
