# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-09-29T08:57:59+00:00

from __future__ import annotations
from open_sport_taxonomy.pydantic import SportField  # OST sport type (see schemas.py)

from datetime import date as date_aliased
from datetime import timedelta
from enum import Enum
from typing import Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    NaiveDatetime,
    BaseModel,
    EmailStr,
    Field,
    RootModel,
    SecretStr,
    confloat,
    conint,
    constr,
)


class Activity(BaseModel):
    id: str = Field(..., title='Id')
    start_date_local: NaiveDatetime | None = Field(None, title='Start Date Local')


class ActivityUpdate(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')


class AltitudeSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    gain: int | float | None = Field(None, title='Gain')
    loss: int | float | None = Field(None, title='Loss')
    min: int | float | None = Field(None, title='Min')
    max: int | float | None = Field(None, title='Max')


class ApplicationCreate(BaseModel):
    name: constr(min_length=1, max_length=100) = Field(..., title='Name')
    description: constr(max_length=500) | None = Field(None, title='Description')
    redirect_uris: list[str] | None = Field(None, title='Redirect Uris')
    page: str | None = Field(None, title='Page')
    generate_secret: bool | None = Field(False, title='Generate Secret')


class ApplicationCreateOrUpdate(BaseModel):
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    url: AnyUrl | None = Field(None, title='Url')
    image: AnyUrl | None = Field(None, title='Image')
    redirect_uris: list[str] | None = Field(None, title='Redirect Uris')
    privacy_statement: AnyUrl | None = Field(None, title='Privacy Statement')
    brand_color: str | None = Field(None, title='Brand Color')
    webhook_endpoints: list[AnyUrl] | None = Field(None, title='Webhook Endpoints')
    webhook_secret: SecretStr | None = Field(None, title='Webhook Secret')


class ApplicationListItem(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    page_slug: str | None = Field(None, title='Page Slug')


class ApplicationMemberRole(Enum):
    owner = 'owner'
    member = 'member'


class Prompt(Enum):
    none = 'none'
    login = 'login'
    consent = 'consent'
    select_account = 'select_account'


class BackfillError(BaseModel):
    error: str = Field(..., title='Error')


class BackfillStatus(BaseModel):
    backfill_loaded_until: AwareDatetime | None = Field(
        ..., title='Backfill Loaded Until'
    )


class BodyAddEmailPartialsAddEmailPost(BaseModel):
    email: EmailStr = Field(..., title='Email')


class BodyCreateApplicationSecretApplicationsApplicationIdSecretsPost(BaseModel):
    label: str = Field(..., title='Label')


class BodyCreatePageApiV1PagesPost(BaseModel):
    application_id: str = Field(..., title='Application Id')
    slug: str = Field(..., title='Slug')


class BodyCreatePageApplicationsApplicationIdPagePost(BaseModel):
    slug: str = Field(..., title='Slug')


class BodyCreateTagTagsPost(BaseModel):
    tag: str = Field(..., title='Tag')


class BodyDeployPageApiV1PagesSlugDeployPut(BaseModel):
    files: list[bytes] = Field(..., title='Files')


class BodyDeployPageApplicationsApplicationIdPageDeployPost(BaseModel):
    files: list[bytes] = Field(..., title='Files')


class BodyEnsureApplicationPageApiV1ApplicationsApplicationIdPagePut(BaseModel):
    slug: str = Field(..., title='Slug')


class BodyLoginPostLoginPost(BaseModel):
    email: EmailStr = Field(..., title='Email')
    state: str | None = Field(None, title='State')


class BodyPortalAddMemberPostPortalUsersUserIdJoinTeamPost(BaseModel):
    team_id: str = Field(..., title='Team Id')


class BodyPortalCreateTeamPortalTeamsPost(BaseModel):
    name: str = Field(..., title='Name')


class BodyPortalPreviewSignInEmailSentDevPortalPreviewSignInEmailSentPost(BaseModel):
    email: str | None = Field('alice@example.com', title='Email')


class BodyPortalSignInPostPortalSignInPost(BaseModel):
    email: EmailStr = Field(..., title='Email')
    next: str | None = Field(None, title='Next')


class BodyPostCreateManagedUserSettingsManagedUsersPost(BaseModel):
    first_name: str = Field(..., title='First Name')
    last_name: str | None = Field(None, title='Last Name')


class BodyPublishSubmitApplicationsApplicationIdPublishPost(BaseModel):
    description: str = Field(..., title='Description')
    url: str | None = Field(None, title='Url')
    image: str | None = Field(None, title='Image')
    privacy_statement: str | None = Field(None, title='Privacy Statement')
    fast_track: bool | None = Field(False, title='Fast Track')


class BodyPutUpdateManagedUserSettingsManagedUsersUserIdPut(BaseModel):
    first_name: str = Field(..., title='First Name')
    last_name: str | None = Field(None, title='Last Name')


class BodyResendMagicLinkPartialsResendMagicLinkPost(BaseModel):
    email: EmailStr = Field(..., title='Email')
    next: str | None = Field(None, title='Next')


class BodySaveOrUpdateIntegrationProviderTenantsTenantIdIntegrationProvidersIntegrationNamePost(
    BaseModel
):
    client_id: str = Field(..., title='Client Id')
    client_secret: SecretStr = Field(..., title='Client Secret')
    redirect_url: str | None = Field(None, title='Redirect Url')
    webhook_secret: SecretStr | None = Field(None, title='Webhook Secret')


class BodyUpdateManagedUserApiV1UsersUserIdPut(BaseModel):
    first_name: str | None = Field(None, title='First Name')
    last_name: str | None = Field(None, title='Last Name')


class BodyUpdateUserUsersUserIdPut(BaseModel):
    first_name: str = Field(..., title='First Name')
    last_name: str = Field(..., title='Last Name')


class BodyUploadActivityFileApiV1ActivitiesUploadPost(BaseModel):
    files: list[bytes] = Field(..., title='Files')


class BodyUploadActivityFileDataUploadPost(BaseModel):
    files: list[bytes] = Field(..., title='Files')


class CadenceSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    max: float | None = Field(None, title='Max')


class Capability(Enum):
    activities = 'activities'
    activity_history = 'activity_history'
    dailies = 'dailies'
    workouts = 'workouts'


class CapabilityStatus(Enum):
    ready = 'ready'
    syncing = 'syncing'
    action_required = 'action_required'
    unavailable = 'unavailable'


class CoreTemperatureSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    min: float | None = Field(None, title='Min')
    max: float | None = Field(None, title='Max')
    start: float | None = Field(None, title='Start')
    end: float | None = Field(None, title='End')


class DailyCreate(BaseModel):
    date: date_aliased = Field(..., title='Date')
    value: float = Field(..., title='Value')


class DailyMeasure(Enum):
    body_mass = 'body_mass'
    body_fat_pct = 'body_fat_pct'
    resting_hr = 'resting_hr'
    hrv = 'hrv'
    sleep_duration = 'sleep_duration'
    sleep_altitude = 'sleep_altitude'
    menstrual_cycle_day = 'menstrual_cycle_day'


class DailySource(Enum):
    manual = 'manual'
    garmin_connect = 'garmin_connect'
    intervals_icu = 'intervals_icu'
    wahoo = 'wahoo'


class DailyStatus(Enum):
    stored = 'stored'
    estimated = 'estimated'
    missing = 'missing'


class DeliveryView(BaseModel):
    integration: str = Field(..., title='Integration')
    status: str = Field(..., title='Status')
    reason: str | None = Field(None, title='Reason')
    detail: str | None = Field(None, title='Detail')
    updated_at: AwareDatetime | None = Field(None, title='Updated At')


class DistanceSummary(BaseModel):
    sum: int | float | None = Field(None, title='Sum')


class Effort(Enum):
    work = 'work'
    rest = 'rest'


class EmailAuthMode(Enum):
    enabled = 'enabled'
    existing_only = 'existing_only'


class GarminBackfillBody(BaseModel):
    start: AwareDatetime = Field(..., title='Start')
    end: AwareDatetime = Field(..., title='End')
    user_id__in: list[str] | None = Field(None, title='User Id  In')
    user_id__not_in: list[str] | None = Field(None, title='User Id  Not In')


class GarminBodyCompSummary(BaseModel):
    userId: str = Field(..., title='Userid')
    measurementTimeInSeconds: int = Field(..., title='Measurementtimeinseconds')
    measurementTimeOffsetInSeconds: int | None = Field(
        0, title='Measurementtimeoffsetinseconds'
    )
    weightInGrams: int | None = Field(None, title='Weightingrams')
    bodyFatInPercent: float | None = Field(None, title='Bodyfatinpercent')


class GarminDailySummary(BaseModel):
    userId: str = Field(..., title='Userid')
    calendarDate: date_aliased = Field(..., title='Calendardate')
    restingHeartRateInBeatsPerMinute: int | None = Field(
        None, title='Restingheartrateinbeatsperminute'
    )


class GarminDeregistration(BaseModel):
    userId: str = Field(..., title='Userid')
    userAccessToken: str = Field(..., title='Useraccesstoken')


class GarminDeregistrationBody(BaseModel):
    deregistrations: list[GarminDeregistration] = Field(..., title='Deregistrations')


class GarminFileTypes(Enum):
    FIT = 'FIT'
    GPX = 'GPX'
    TCX = 'TCX'


class GarminHrvSummary(BaseModel):
    userId: str = Field(..., title='Userid')
    calendarDate: date_aliased | None = Field(None, title='Calendardate')
    lastNightAvg: int | None = Field(None, title='Lastnightavg')


class GarminPermissionGap(Enum):
    activities = 'activities'
    history = 'history'


class GarminSleepSummary(BaseModel):
    userId: str = Field(..., title='Userid')
    calendarDate: date_aliased | None = Field(None, title='Calendardate')
    durationInSeconds: int | None = Field(None, title='Durationinseconds')
    validation: str | None = Field(None, title='Validation')


class GarminUserPermissionChange(BaseModel):
    userId: str = Field(..., title='Userid')
    userAccessToken: str = Field(..., title='Useraccesstoken')
    permissions: list[str] = Field(..., title='Permissions')


class GarminUserPermissionsBody(BaseModel):
    userPermissionsChange: list[GarminUserPermissionChange] = Field(
        ..., title='Userpermissionschange'
    )


class GrantType(Enum):
    authorization_code = 'authorization_code'
    refresh_token = 'refresh_token'


class HeartRateSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    min: float | None = Field(None, title='Min')
    max: float | None = Field(None, title='Max')
    start: float | None = Field(None, title='Start')
    end: float | None = Field(None, title='End')


class IntegrationName(Enum):
    garmin_connect = 'garmin_connect'
    intervals_icu = 'intervals_icu'
    wahoo = 'wahoo'


class IntensityDurationModelPoint(BaseModel):
    duration: int = Field(..., description='Seconds.', title='Duration')
    intensity: float = Field(
        ...,
        description='Modeled intensity at that duration: whole W for power, m/s to 2 decimals for speed.',
        title='Intensity',
    )


class IntensityDurationModelResponse(BaseModel):
    curve: list[IntensityDurationModelPoint] = Field(..., title='Curve')


class IntensityQuantity(Enum):
    speed = 'speed'
    power = 'power'
    heart_rate = 'heart_rate'
    rpe_cr10 = 'rpe_cr10'
    rpe_borg = 'rpe_borg'


class IntervalsIcuWebhookEventType(Enum):
    APP_SCOPE_CHANGED = 'APP_SCOPE_CHANGED'
    CALENDAR_UPDATED = 'CALENDAR_UPDATED'
    CALENDAR_EVENT_UPDATED = 'CALENDAR_EVENT_UPDATED'
    CALENDAR_EVENT_DELETED = 'CALENDAR_EVENT_DELETED'
    ACTIVITY_UPLOADED = 'ACTIVITY_UPLOADED'
    ACTIVITY_ANALYZED = 'ACTIVITY_ANALYZED'
    ACTIVITY_UPDATED = 'ACTIVITY_UPDATED'
    ACTIVITY_DELETED = 'ACTIVITY_DELETED'
    ACTIVITY_ACHIEVEMENTS = 'ACTIVITY_ACHIEVEMENTS'
    WELLNESS_UPDATED = 'WELLNESS_UPDATED'
    FITNESS_UPDATED = 'FITNESS_UPDATED'


class ManagedUserCreate(BaseModel):
    first_name: str = Field(..., title='First Name')
    last_name: str | None = Field(..., title='Last Name')


class Marker(BaseModel):
    power: int | None = Field(None, title='Power')
    speed: float | None = Field(None, title='Speed')
    heart_rate: int | None = Field(None, title='Heart Rate')
    lactate: float | None = Field(None, title='Lactate')
    vo2: float | None = Field(None, title='Vo2')


class MetabolicMapResponse(BaseModel):
    body_mass: float = Field(
        ...,
        description="Body mass used, in kg to 1 decimal: the user's daily on `date`, estimated from the nearest records when none was logged that day.",
        title='Body Mass',
    )
    critical_intensity: float = Field(
        ...,
        description='Critical power (W) or critical speed (m/s): the threshold to build zones and targets on.',
        title='Critical Intensity',
    )
    mlss: float = Field(
        ...,
        description='Maximum lactate steady state intensity (W or m/s).',
        title='Mlss',
    )
    vo2max: float = Field(
        ...,
        description='Maximum oxygen uptake, absolute, in whole mL/min. Divide by `body_mass` for mL/kg/min.',
        title='Vo2Max',
    )
    max_aerobic_intensity: float = Field(
        ...,
        description='Maximal aerobic power (W) or speed (m/s): the intensity at which oxygen uptake reaches VO2max.',
        title='Max Aerobic Intensity',
    )
    fatmax: float | None = Field(
        ...,
        description='Intensity at maximum fat oxidation (W or m/s). Null when fat oxidation never peaks inside the modeled range.',
        title='Fatmax',
    )


class Metric(Enum):
    duration = 'duration'
    lap = 'lap'
    power = 'power'
    speed = 'speed'
    heart_rate = 'heart_rate'
    respiration_rate = 'respiration_rate'
    smo2 = 'smo2'
    core_temperature = 'core_temperature'
    elevation = 'elevation'
    altitude = 'altitude'
    cadence = 'cadence'
    temperature = 'temperature'
    distance = 'distance'
    longitude = 'longitude'
    latitude = 'latitude'
    lactate = 'lactate'
    rpe = 'rpe'
    notes = 'notes'


class Note(BaseModel):
    type: Literal['note'] = Field('note', title='Type')
    text: str = Field(..., title='Text')


class PageApplicationInfo(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    is_private: bool = Field(..., title='Is Private')


class PageResponse(BaseModel):
    slug: str = Field(..., title='Slug')
    published: bool = Field(..., title='Published')
    application: PageApplicationInfo
    url: str = Field(
        ..., description='The public URL where this page is served.', title='Url'
    )


class ParameterRef(BaseModel):
    percent: int | float = Field(..., title='Percent')
    of: str = Field(..., title='Of')


class PortalDestination(Enum):
    manage_teams = 'manage-teams'
    manage_integrations = 'manage-integrations'


class PortalSessionRequest(BaseModel):
    client_id: str = Field(..., title='Client Id')
    client_secret: SecretStr | None = Field(None, title='Client Secret')
    destination: PortalDestination
    return_url: str | None = Field(None, title='Return Url')


class PortalSessionResponse(BaseModel):
    url: str = Field(..., title='Url')


class PortalSignInState(BaseModel):
    next: str = Field(..., title='Next')


class PowerSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    max: float | None = Field(None, title='Max')


class RepeatCount(BaseModel):
    min: int = Field(..., title='Min')
    max: int = Field(..., title='Max')


class Scope(Enum):
    data_read = 'data:read'
    data_write = 'data:write'
    admin = 'admin'
    openid = 'openid'
    profile = 'profile'
    offline_access = 'offline_access'


class SectionPhase(Enum):
    warmup = 'warmup'
    main = 'main'
    cooldown = 'cooldown'


class Smo2Summary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    min: float | None = Field(None, title='Min')
    max: float | None = Field(None, title='Max')
    start: float | None = Field(None, title='Start')
    end: float | None = Field(None, title='End')


class SourceError(BaseModel):
    code: str = Field(..., title='Code')
    message: str | None = Field(None, title='Message')


class SourceOrigin(Enum):
    manual_upload = 'manual_upload'
    garmin_connect = 'garmin_connect'
    intervals_icu = 'intervals_icu'
    wahoo = 'wahoo'


class SourceResponse(BaseModel):
    id: str = Field(..., title='Id')
    type: str | None = Field(..., title='Type')
    origin: str = Field(..., title='Origin')
    filename: str | None = Field(..., title='Filename')
    status: str = Field(..., title='Status')
    error: SourceError | None = None
    activity_ids: list[str] = Field(..., title='Activity Ids')
    created_at: AwareDatetime = Field(..., title='Created At')


class SourceStatus(Enum):
    processing = 'processing'
    processed = 'processed'
    failed = 'failed'


class SpeedSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    max: float | None = Field(None, title='Max')




class StatusIssueCode(Enum):
    no_source_connected = 'no_source_connected'
    activities_not_granted = 'activities_not_granted'
    activity_history_not_granted = 'activity_history_not_granted'
    dailies_not_granted = 'dailies_not_granted'
    workouts_not_granted = 'workouts_not_granted'
    sync_pending = 'sync_pending'
    activity_history_unavailable = 'activity_history_unavailable'
    dailies_unavailable = 'dailies_unavailable'
    workouts_unavailable = 'workouts_unavailable'


class StatusIssueResponse(BaseModel):
    code: StatusIssueCode
    status: CapabilityStatus
    message: str = Field(..., title='Message')
    action_url: str | None = Field(None, title='Action Url')


class TTERef(BaseModel):
    tte: int | float = Field(..., title='Tte')


class TeamCreateOrUpdate(BaseModel):
    name: str = Field(..., title='Name')
    description: str = Field(..., title='Description')
    url: AnyUrl = Field(..., title='Url')
    image: AnyUrl = Field(..., title='Image')
    privacy_statement: AnyUrl = Field(..., title='Privacy Statement')


class TeamResponse(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str = Field(..., title='Description')
    url: AnyUrl = Field(..., title='Url')
    image: AnyUrl = Field(..., title='Image')
    privacy_statement: AnyUrl = Field(..., title='Privacy Statement')
    role: ApplicationMemberRole | None


class TemperatureSummary(BaseModel):
    mean: float | None = Field(None, title='Mean')
    min: float | None = Field(None, title='Min')
    max: float | None = Field(None, title='Max')
    start: float | None = Field(None, title='Start')
    end: float | None = Field(None, title='End')


class TemplateDay(BaseModel):
    sports: list[SportField] = Field(..., title='Sports')
    avg_training_duration: timedelta = Field(..., title='Avg Training Duration')
    typical_training_duration: timedelta = Field(..., title='Typical Training Duration')


class TemplateWeekResponse(BaseModel):
    monday: TemplateDay
    tuesday: TemplateDay
    wednesday: TemplateDay
    thursday: TemplateDay
    friday: TemplateDay
    saturday: TemplateDay
    sunday: TemplateDay


class TestResults(BaseModel):
    first_threshold: Marker | None = None
    second_threshold: Marker | None = None
    fatmax: Marker | None = None
    lt1: Marker | None = None
    lt2: Marker | None = None
    vt1: Marker | None = None
    vt2: Marker | None = None
    mlss: Marker | None = None
    vo2max: float | None = Field(None, title='Vo2Max')
    vo2peak: float | None = Field(None, title='Vo2Peak')
    vlamax: float | None = Field(None, title='Vlamax')
    heart_rate_max: int | None = Field(None, title='Heart Rate Max')
    critical_power: int | None = Field(None, title='Critical Power')
    critical_speed: float | None = Field(None, title='Critical Speed')
    w_prime: float | None = Field(None, title='W Prime')
    d_prime: float | None = Field(None, title='D Prime')
    economy: float | None = Field(None, title='Economy')
    efficiency: float | None = Field(None, title='Efficiency')


class TestSummary(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    created_by: str | None = Field(None, title='Created By')
    title: str | None = Field(None, title='Title')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    start: AwareDatetime = Field(
        ...,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='Start',
    )
    end: AwareDatetime | None = Field(
        None,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='End',
    )
    results: TestResults | None = None
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    start_local: NaiveDatetime = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='Start Local',
    )
    end_local: NaiveDatetime | None = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='End Local',
    )


class TestUpdate(BaseModel):
    title: str | None = Field(None, title='Title')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    start: AwareDatetime = Field(
        ...,
        description='Offset-aware ISO 8601 (e.g. `2026-05-18T17:32:00+02:00` or `...Z`). A naive timestamp is rejected; the offset is stored so the local time round-trips.',
        title='Start',
    )
    end: AwareDatetime | None = Field(
        None,
        description='Offset-aware ISO 8601 (e.g. `2026-05-18T17:32:00+02:00` or `...Z`). A naive timestamp is rejected; the offset is stored so the local time round-trips.',
        title='End',
    )
    results: TestResults | None = None
    tags: list[str] | None = Field(None, title='Tags')


class TokenRequest(BaseModel):
    grant_type: GrantType
    client_id: str | None = Field(None, title='Client Id')
    code: str | None = Field(None, title='Code')
    client_secret: str | None = Field(None, title='Client Secret')
    code_verifier: str | None = Field(None, title='Code Verifier')
    refresh_token: str | None = Field(None, title='Refresh Token')


class TokenResponse(BaseModel):
    access_token: str = Field(..., title='Access Token')
    token_type: Literal['Bearer'] = Field('Bearer', title='Token Type')
    expires_in: int = Field(..., title='Expires In')
    refresh_token: str | None = Field(None, title='Refresh Token')
    scope: str | None = Field(None, title='Scope')
    id_token: str | None = Field(None, title='Id Token')


class TraceCreateOrUpdate(BaseModel):
    timestamp: AwareDatetime = Field(
        ...,
        description='Offset-aware ISO 8601 (e.g. `2026-05-18T17:32:00+02:00` or `...Z`). A naive timestamp is rejected; the offset is stored so the local time round-trips.',
        title='Timestamp',
    )
    test_id: str | None = Field(None, title='Test Id')
    lactate: float | None = Field(None, title='Lactate')
    rpe: int | None = Field(None, title='Rpe')
    notes: str | None = Field(None, title='Notes')
    power: conint(ge=0) | None = Field(None, title='Power')
    speed: confloat(ge=0.0) | None = Field(None, title='Speed')
    heart_rate: conint(ge=0) | None = Field(None, title='Heart Rate')
    vo2: confloat(ge=0.0) | None = Field(None, title='Vo2')
    tags: list[str] | None = Field(None, title='Tags')
    sport: SportField | None = None


class TestMatch(Enum):
    explicit = 'explicit'
    window = 'window'


class TraceResolution(Enum):
    auto = 'auto'
    linked = 'linked'


class UserFlow(Enum):
    session = 'session'
    signup = 'signup'
    login = 'login'


class UserInfoResponse(BaseModel):
    sub: str = Field(..., title='Sub')
    given_name: str | None = Field(None, title='Given Name')
    family_name: str | None = Field(None, title='Family Name')
    email: str | None = Field(None, title='Email')
    registered_at: AwareDatetime | NaiveDatetime = Field(..., title='Registered At')
    issue: StatusIssueResponse | None = None
    name: str = Field(..., title='Name')


class UserResponse(BaseModel):
    id: str = Field(..., title='Id')
    first_name: str | None = Field(..., title='First Name')
    last_name: str | None = Field(..., title='Last Name')
    admin: bool = Field(..., title='Admin')
    registered_at: AwareDatetime | NaiveDatetime = Field(..., title='Registered At')
    display_name: str = Field(..., title='Display Name')
    is_managed: bool = Field(..., title='Is Managed')


class UserSummary(BaseModel):
    id: str = Field(..., title='Id')
    first_name: str | None = Field(..., title='First Name')
    last_name: str | None = Field(..., title='Last Name')
    scopes: list[Scope] = Field(..., title='Scopes')
    display_name: str = Field(..., title='Display Name')
    is_managed: bool = Field(..., title='Is Managed')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class VolumeQuantity(Enum):
    duration = 'duration'
    distance = 'distance'


class WahooFile(BaseModel):
    url: str | None = Field(None, title='Url')


class WahooWebhookUser(BaseModel):
    id: int = Field(..., title='Id')


class WahooWorkoutRef(BaseModel):
    id: int | None = Field(None, title='Id')
    starts: AwareDatetime | None = Field(None, title='Starts')


class WahooWorkoutSummary(BaseModel):
    id: int | None = Field(None, title='Id')
    file: WahooFile | None = None
    workout: WahooWorkoutRef | None = None


class WebhookEventType(Enum):
    activity_created = 'activity_created'
    activity_updated = 'activity_updated'
    activity_deleted = 'activity_deleted'
    test_created = 'test_created'
    test_updated = 'test_updated'
    test_deleted = 'test_deleted'
    source_processed = 'source_processed'
    source_failed = 'source_failed'


class WorkoutWarning(BaseModel):
    integration: str = Field(..., title='Integration')
    issues: list[dict[str, Any]] | None = Field(None, title='Issues')
    adjustments: list[dict[str, Any]] | None = Field(None, title='Adjustments')


class ZoneValue(BaseModel):
    type: Literal['zone'] = Field('zone', title='Type')
    quantity: IntensityQuantity
    zone: int = Field(..., title='Zone')
    of: int = Field(..., title='Of')


class AccountStatusResponse(BaseModel):
    issue: StatusIssueResponse | None = None
    capabilities: dict[Capability, CapabilityStatus] = Field(..., title='Capabilities')


class ActivitySummarySummary(BaseModel):
    power: PowerSummary | None = None
    speed: SpeedSummary | None = None
    distance: DistanceSummary | None = None
    altitude: AltitudeSummary | None = None
    heart_rate: HeartRateSummary | None = None
    cadence: CadenceSummary | None = None
    temperature: TemperatureSummary | None = None
    core_temperature: CoreTemperatureSummary | None = None
    smo2: Smo2Summary | None = None


class ApplicationCreateResponse(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    image: AnyUrl | None = Field(None, title='Image')
    url: AnyUrl | None = Field(None, title='Url')
    redirect_uris: list[str] | None = Field(None, title='Redirect Uris')
    privacy_statement: AnyUrl | None = Field(None, title='Privacy Statement')
    brand_color: str | None = Field(None, title='Brand Color')
    published: bool | None = Field(
        False,
        deprecated=True,
        description='The App Directory is retired. Reflects the last stored listing; removed on 2026-10-12.',
        title='Published',
    )
    webhook_endpoints: list[AnyUrl] | None = Field(None, title='Webhook Endpoints')
    webhook_secret: SecretStr | None = Field(None, title='Webhook Secret')
    client_secret: str | None = Field(None, title='Client Secret')
    page: PageResponse | None = None
    is_private: bool = Field(
        ...,
        description='An application is private if it is missing any of: description, URL, image, or privacy statement.',
        title='Is Private',
    )
    is_clientside_app: bool = Field(
        ...,
        description='Check if this is a client-side app based on privacy policy URL.\n\nApps that went live through the Pages one-click path have privacy_statement set to\nthe standard client-side privacy policy URL: that is their attestation.',
        title='Is Clientside App',
    )


class AuthorizeQueryParams(BaseModel):
    client_id: str = Field(..., title='Client Id')
    redirect_uri: str | None = Field(None, title='Redirect Uri')
    scope: list[Scope] = Field(..., min_length=1, title='Scope')
    state: str | None = Field(None, title='State')
    nonce: str | None = Field(None, title='Nonce')
    code_challenge: str | None = Field(None, title='Code Challenge')
    code_challenge_method: str | None = Field(None, title='Code Challenge Method')
    prompt: Prompt | None = Field('consent', title='Prompt')
    user_flow: UserFlow | None = 'session'
    email_auth_mode: EmailAuthMode | None = 'enabled'
    integration: IntegrationName | None = None


class AuthorizeTeamRequest(BaseModel):
    scopes: list[Scope] = Field(..., title='Scopes')


class AuthorizedTeamResponse(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str = Field(..., title='Description')
    url: AnyUrl = Field(..., title='Url')
    image: AnyUrl = Field(..., title='Image')
    privacy_statement: AnyUrl = Field(..., title='Privacy Statement')
    scopes: list[Scope] = Field(..., title='Scopes')


class BodyAuthorizeOauthAuthorizePost(BaseModel):
    client_id: str = Field(..., title='Client Id')
    redirect_uri: str | None = Field(None, title='Redirect Uri')
    scopes: list[Scope] = Field(..., min_length=1, title='Scopes')
    state: str | None = Field(None, title='State')
    nonce: str | None = Field(None, title='Nonce')
    code_challenge: str | None = Field(None, title='Code Challenge')
    code_challenge_method: str | None = Field(None, title='Code Challenge Method')
    email: str | None = Field(None, title='Email')
    integration: IntegrationName | Literal[''] | None = Field(None, title='Integration')
    email_auth_mode: EmailAuthMode | None = 'enabled'


class BodyCreateDailyDataDailiesPost(BaseModel):
    measure: DailyMeasure
    date: date_aliased = Field(..., title='Date')
    value: float = Field(..., title='Value')


class BodyGenerateApiKeyPartialsGenerateApiKeyPost(BaseModel):
    scopes: list[Scope] = Field(..., title='Scopes')


class ConstantValue(BaseModel):
    type: Literal['constant'] = Field('constant', title='Type')
    quantity: VolumeQuantity | IntensityQuantity = Field(..., title='Quantity')
    value: int | float | ParameterRef | TTERef = Field(..., title='Value')


class DailyResponse(BaseModel):
    date: date_aliased = Field(..., title='Date')
    value: float | None = Field(..., title='Value')
    status: DailyStatus
    source: DailySource | None = None


class DelegatedTokenRequest(BaseModel):
    sub: str = Field(..., title='Sub')
    scopes: list[Scope] | None = Field(None, title='Scopes')
    team_id: str | None = Field(None, title='Team Id')


class GarminActivityFileData(BaseModel):
    userId: str = Field(..., title='Userid')
    userAccessToken: str = Field(..., title='Useraccesstoken')
    summaryId: str = Field(..., title='Summaryid')
    fileType: GarminFileTypes
    callbackURL: str = Field(..., title='Callbackurl')
    startTimeInSeconds: AwareDatetime = Field(..., title='Starttimeinseconds')
    activityId: str = Field(..., title='Activityid')
    activityName: str | None = Field(None, title='Activityname')
    manual: bool | None = Field(False, title='Manual')


class GarminHealthPushBody(BaseModel):
    dailies: list[GarminDailySummary] | None = Field(None, title='Dailies')
    sleeps: list[GarminSleepSummary] | None = Field(None, title='Sleeps')
    bodyComps: list[GarminBodyCompSummary] | None = Field(None, title='Bodycomps')
    hrv: list[GarminHrvSummary] | None = Field(None, title='Hrv')


class GarminPingBody(BaseModel):
    activityFiles: list[GarminActivityFileData] = Field(..., title='Activityfiles')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class IntervalsIcuWebhookEvent(BaseModel):
    athlete_id: str = Field(..., title='Athlete Id')
    type: IntervalsIcuWebhookEventType
    timestamp: AwareDatetime = Field(..., title='Timestamp')
    activity: Activity


class Lap(BaseModel):
    power: PowerSummary | None = None
    speed: SpeedSummary | None = None
    distance: DistanceSummary | None = None
    altitude: AltitudeSummary | None = None
    heart_rate: HeartRateSummary | None = None
    cadence: CadenceSummary | None = None
    temperature: TemperatureSummary | None = None
    core_temperature: CoreTemperatureSummary | None = None
    smo2: Smo2Summary | None = None
    start: AwareDatetime = Field(
        ...,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='Start',
    )
    end: AwareDatetime = Field(
        ...,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='End',
    )
    duration: timedelta = Field(..., title='Duration')
    start_local: NaiveDatetime = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='Start Local',
    )
    end_local: NaiveDatetime = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='End Local',
    )


class RampValue(BaseModel):
    type: Literal['ramp'] = Field('ramp', title='Type')
    quantity: VolumeQuantity | IntensityQuantity = Field(..., title='Quantity')
    start: int | float | ParameterRef | TTERef = Field(..., title='Start')
    end: int | float | ParameterRef | TTERef = Field(..., title='End')


class RangeValue(BaseModel):
    type: Literal['range'] = Field('range', title='Type')
    quantity: VolumeQuantity | IntensityQuantity = Field(..., title='Quantity')
    min: int | float | ParameterRef | TTERef | None = Field(None, title='Min')
    max: int | float | ParameterRef | TTERef | None = Field(None, title='Max')


class StepInput(BaseModel):
    type: Literal['step'] = Field('step', title='Type')
    effort: Effort | None = 'work'
    note: str | None = Field(None, title='Note')
    volume: ConstantValue | RangeValue | RampValue | ZoneValue | None = Field(
        None, title='Volume'
    )
    intensity: ConstantValue | RangeValue | RampValue | ZoneValue | None = Field(
        None, title='Intensity'
    )


class StepOutput(BaseModel):
    type: Literal['step'] = Field('step', title='Type')
    effort: Effort | None = 'work'
    note: str | None = Field(None, title='Note')
    volume: ConstantValue | RangeValue | RampValue | ZoneValue | None = Field(
        None, title='Volume'
    )
    intensity: ConstantValue | RangeValue | RampValue | ZoneValue | None = Field(
        None, title='Intensity'
    )


class TestCreate(BaseModel):
    title: str | None = Field(None, title='Title')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    start: AwareDatetime = Field(
        ...,
        description='Offset-aware ISO 8601 (e.g. `2026-05-18T17:32:00+02:00` or `...Z`). A naive timestamp is rejected; the offset is stored so the local time round-trips.',
        title='Start',
    )
    end: AwareDatetime | None = Field(
        None,
        description='Offset-aware ISO 8601 (e.g. `2026-05-18T17:32:00+02:00` or `...Z`). A naive timestamp is rejected; the offset is stored so the local time round-trips.',
        title='End',
    )
    results: TestResults | None = None
    tags: list[str] | None = Field(None, title='Tags')


class WahooWebhookBody(BaseModel):
    event_type: str = Field(..., title='Event Type')
    webhook_token: str = Field(..., title='Webhook Token')
    user: WahooWebhookUser
    workout_summary: WahooWorkoutSummary | None = None


class WebhookEventBody(BaseModel):
    user_id: str = Field(..., title='User Id')
    event_type: WebhookEventType
    resource_id: str | None = Field(..., title='Resource Id')
    timestamp: AwareDatetime = Field(..., title='Timestamp')


class IntervalsIcuWebhookBody(BaseModel):
    secret: str = Field(..., title='Secret')
    events: list[IntervalsIcuWebhookEvent] = Field(..., title='Events')


class ActivityDetails(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    start: AwareDatetime = Field(
        ...,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='Start',
    )
    end: AwareDatetime = Field(
        ...,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='End',
    )
    metrics: list[Metric] = Field(..., title='Metrics')
    source_id: str = Field(..., title='Source Id')
    summary: ActivitySummarySummary | None = None
    laps: list[Lap] | None = Field(None, title='Laps')
    traces: list[TraceDetails] | None = Field(None, title='Traces')
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    distance: float | None = Field(None, title='Distance')
    devices: list[str] | None = Field(None, title='Devices')
    duration: timedelta = Field(..., title='Duration')
    start_local: NaiveDatetime = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='Start Local',
    )
    end_local: NaiveDatetime = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='End Local',
    )


class ActivitySummary(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    start: AwareDatetime = Field(
        ...,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='Start',
    )
    end: AwareDatetime = Field(
        ...,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='End',
    )
    metrics: list[Metric] = Field(..., title='Metrics')
    source_id: str = Field(..., title='Source Id')
    summary: ActivitySummarySummary | None = None
    laps: list[Lap] | None = Field(None, title='Laps')
    traces: list[TraceDetails] | None = Field(None, title='Traces')
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    duration: timedelta = Field(..., title='Duration')
    start_local: NaiveDatetime = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='Start Local',
    )
    end_local: NaiveDatetime = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='End Local',
    )


class RepeatInput(BaseModel):
    type: Literal['repeat'] = Field('repeat', title='Type')
    note: str | None = Field(None, title='Note')
    count: int | ParameterRef | RepeatCount = Field(..., title='Count')
    content: list[Content] = Field(..., title='Content')


class RepeatOutput(BaseModel):
    type: Literal['repeat'] = Field('repeat', title='Type')
    note: str | None = Field(None, title='Note')
    count: int | ParameterRef | RepeatCount = Field(..., title='Count')
    content: list[Content1] = Field(..., title='Content')


class ScheduledWorkoutCreate(BaseModel):
    swf: WorkoutInput
    start: AwareDatetime = Field(
        ...,
        description="Naive local datetime (ISO 8601 without an offset, e.g. `2026-05-25T07:00:00`). A scheduled workout is a plan in the athlete's local wall-clock, so this carries no timezone.",
        title='Start',
    )
    parameters: dict[str, float] | None = Field(None, title='Parameters')


class ScheduledWorkoutCreateResponse(BaseModel):
    id: str = Field(..., title='Id')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    start: AwareDatetime = Field(
        ...,
        description="Naive local datetime (ISO 8601 without an offset, e.g. `2026-05-25T07:00:00`). A scheduled workout is a plan in the athlete's local wall-clock, so this carries no timezone.",
        title='Start',
    )
    swf: WorkoutOutput
    parameters: dict[str, float] | None = Field(None, title='Parameters')
    application_id: str | None = Field(None, title='Application Id')
    application_name: str | None = Field(None, title='Application Name')
    deliveries: list[DeliveryView] | None = Field(None, title='Deliveries')
    warnings: list[WorkoutWarning] | None = Field(None, title='Warnings')


class ScheduledWorkoutResponse(BaseModel):
    id: str = Field(..., title='Id')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    start: AwareDatetime = Field(
        ...,
        description="Naive local datetime (ISO 8601 without an offset, e.g. `2026-05-25T07:00:00`). A scheduled workout is a plan in the athlete's local wall-clock, so this carries no timezone.",
        title='Start',
    )
    swf: WorkoutOutput
    parameters: dict[str, float] | None = Field(None, title='Parameters')
    application_id: str | None = Field(None, title='Application Id')
    application_name: str | None = Field(None, title='Application Name')
    deliveries: list[DeliveryView] | None = Field(None, title='Deliveries')


class SectionInput(BaseModel):
    type: Literal['section'] = Field('section', title='Type')
    note: str | None = Field(None, title='Note')
    phase: SectionPhase
    content: list[Content] = Field(..., title='Content')


class SectionOutput(BaseModel):
    type: Literal['section'] = Field('section', title='Type')
    note: str | None = Field(None, title='Note')
    phase: SectionPhase
    content: list[Content1] = Field(..., title='Content')


class TestDetails(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    created_by: str | None = Field(None, title='Created By')
    title: str | None = Field(None, title='Title')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    start: AwareDatetime = Field(
        ...,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='Start',
    )
    end: AwareDatetime | None = Field(
        None,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='End',
    )
    results: TestResults | None = None
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    traces: list[TraceDetails] | None = Field(None, title='Traces')
    activities: list[ActivitySummary] | None = Field(None, title='Activities')
    start_local: NaiveDatetime = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='Start Local',
    )
    end_local: NaiveDatetime | None = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='End Local',
    )


class TraceDetails(BaseModel):
    tags: list[str] | None = Field(None, title='Tags')
    id: str = Field(..., title='Id')
    test_id: str | None = Field(None, title='Test Id')
    timestamp: AwareDatetime = Field(
        ...,
        description='Absolute instant in UTC (ISO 8601 with `Z`, e.g. `2026-05-18T15:32:00Z`). Sort, compare and merge on this; for the local wall-clock use the matching `*_local` field.',
        title='Timestamp',
    )
    lactate: float | None = Field(None, title='Lactate')
    rpe: int | None = Field(None, title='Rpe')
    notes: str | None = Field(None, title='Notes')
    power: conint(ge=0) | None = Field(None, title='Power')
    speed: confloat(ge=0.0) | None = Field(None, title='Speed')
    heart_rate: conint(ge=0) | None = Field(None, title='Heart Rate')
    vo2: confloat(ge=0.0) | None = Field(None, title='Vo2')
    lap: Lap | None = None
    activity: ActivitySummary | None = None
    test: TestSummary | None = None
    test_match: TestMatch | None = Field(None, title='Test Match')
    sport: SportField | None = None
    app_metadata: dict[str, Any] | None = Field(None, title='App Metadata')
    timestamp_local: NaiveDatetime = Field(
        ...,
        description="Naive local wall-clock at the record's own place/time (ISO 8601 without an offset, e.g. `2026-05-18T17:32:00`). Use for display and for grouping by local calendar date.",
        title='Timestamp Local',
    )


class WorkoutInput(BaseModel):
    field_schema: str | None = Field(None, alias='$schema', title='$Schema')
    version: str | None = Field('0.4.0', title='Version')
    title: str | None = Field(None, title='Title')
    description: str | None = Field(None, title='Description')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    pool_length: int | float | None = Field(None, title='Pool Length')
    content: list[Content4] = Field(..., title='Content')


class WorkoutOutput(BaseModel):
    field_schema: str | None = Field(None, alias='$schema', title='$Schema')
    version: str | None = Field('0.4.0', title='Version')
    title: str | None = Field(None, title='Title')
    description: str | None = Field(None, title='Description')
    sport: SportField = Field(
        ...,
        description="Sport string in OpenSportTaxonomy format (e.g., 'cycling.road+stationary')",
    )
    pool_length: int | float | None = Field(None, title='Pool Length')
    content: list[Content5] = Field(..., title='Content')


class Content(RootModel[StepInput | RepeatInput | Note]):
    root: StepInput | RepeatInput | Note = Field(..., discriminator='type')


class Content1(RootModel[StepOutput | RepeatOutput | Note]):
    root: StepOutput | RepeatOutput | Note = Field(..., discriminator='type')


class Content4(RootModel[StepInput | RepeatInput | SectionInput | Note]):
    root: StepInput | RepeatInput | SectionInput | Note = Field(
        ..., discriminator='type'
    )


class Content5(RootModel[StepOutput | RepeatOutput | SectionOutput | Note]):
    root: StepOutput | RepeatOutput | SectionOutput | Note = Field(
        ..., discriminator='type'
    )


ActivityDetails.model_rebuild()
ActivitySummary.model_rebuild()
RepeatInput.model_rebuild()
RepeatOutput.model_rebuild()
ScheduledWorkoutCreate.model_rebuild()
ScheduledWorkoutCreateResponse.model_rebuild()
ScheduledWorkoutResponse.model_rebuild()
SectionInput.model_rebuild()
SectionOutput.model_rebuild()
TestDetails.model_rebuild()
WorkoutInput.model_rebuild()
WorkoutOutput.model_rebuild()
